// This file was automatically generated by mq. DO NOT EDIT.
package noreturn

import (
	"fmt"
	"github.com/lukejoshuapark/mq"
)

// MockLogger is a mock implementation of the Logger interface.
type MockLogger struct {
	logSetups []MockLoggerLogSetup
	logCalls []MockLoggerLogCall
	logWithLevelSetups []MockLoggerLogWithLevelSetup
	logWithLevelCalls []MockLoggerLogWithLevelCall
}

var _ Logger = &MockLogger{}

// NewMockLogger creates a new instance of MockLogger.
func NewMockLogger() *MockLogger {
	return &MockLogger{}
}

type MockLoggerLogSetup struct {
	message mq.Input[string]
}

type MockLoggerLogCall struct {
	message string
}

// SetupLog configures the mock to return specific outputs when Log is called with matching inputs.
func (m *MockLogger) SetupLog(message mq.Input[string]) {
	m.logSetups = append(m.logSetups, MockLoggerLogSetup{
		message: message,
	})
}

// VerifyLog checks that Log was called the expected number of times with matching inputs.
func (m *MockLogger) VerifyLog(count mq.Count, message mq.Input[string]) {
	c := 0

	for _, call := range m.logCalls {
		if message.Compare(call.message) {
			c++
		}
	}

	if !count.ShouldPass(c) {
		panic(fmt.Sprintf("mock verification failed for Logger.Log: expected count not met (actual: %d)", c))
	}
}

func (m *MockLogger) Log(message string) () {
	for _, setup := range m.logSetups {
		if setup.message.Compare(message) {
			m.logCalls = append(m.logCalls, MockLoggerLogCall{
				message: message,
			})

			return 
		}
	}

	panic("no mock setup found for MockLogger.Log with the provided arguments")
}

type MockLoggerLogWithLevelSetup struct {
	level mq.Input[string]
	message mq.Input[string]
}

type MockLoggerLogWithLevelCall struct {
	level string
	message string
}

// SetupLogWithLevel configures the mock to return specific outputs when LogWithLevel is called with matching inputs.
func (m *MockLogger) SetupLogWithLevel(level mq.Input[string], message mq.Input[string]) {
	m.logWithLevelSetups = append(m.logWithLevelSetups, MockLoggerLogWithLevelSetup{
		level: level,
		message: message,
	})
}

// VerifyLogWithLevel checks that LogWithLevel was called the expected number of times with matching inputs.
func (m *MockLogger) VerifyLogWithLevel(count mq.Count, level mq.Input[string], message mq.Input[string]) {
	c := 0

	for _, call := range m.logWithLevelCalls {
		if level.Compare(call.level) && message.Compare(call.message) {
			c++
		}
	}

	if !count.ShouldPass(c) {
		panic(fmt.Sprintf("mock verification failed for Logger.LogWithLevel: expected count not met (actual: %d)", c))
	}
}

func (m *MockLogger) LogWithLevel(level string, message string) () {
	for _, setup := range m.logWithLevelSetups {
		if setup.level.Compare(level) && setup.message.Compare(message) {
			m.logWithLevelCalls = append(m.logWithLevelCalls, MockLoggerLogWithLevelCall{
				level: level,
				message: message,
			})

			return 
		}
	}

	panic("no mock setup found for MockLogger.LogWithLevel with the provided arguments")
}

