// This file was automatically generated by mq. DO NOT EDIT.
package noreturn

import (
	"fmt"
	"github.com/lukejoshuapark/mq"
)

// MockLogger is a mock implementation of the Logger interface.
type MockLogger struct {
	logSetups []MockLoggerLogSetup
	logCalls []MockLoggerLogCall
	logWithLevelSetups []MockLoggerLogWithLevelSetup
	logWithLevelCalls []MockLoggerLogWithLevelCall
}

// NewMockLogger creates a new instance of MockLogger.
func NewMockLogger() *MockLogger {
	return &MockLogger{}
}

type MockLoggerLogSetup struct {
	message mq.Input[string]
}

type MockLoggerLogCall struct {
	message string
}

// SetupLog configures the mock to return specific outputs when Log is called with matching inputs.
func (m *MockLogger) SetupLog(message mq.Input[string]) {
	m.logSetups = append(m.logSetups, MockLoggerLogSetup{
		message: message,
	})
}

// VerifyLog checks that Log was called the expected number of times with matching inputs.
func (m *MockLogger) VerifyLog(count mq.Count, message mq.Input[string]) {
	c := 0

	for _, call := range m.logCalls {
		if message.Compare(call.message) {
			c++
		}
	}

	if !count.ShouldPass(c) {
		msg := fmt.Sprintf("mock verification failed for Logger.Log: expected %s (count: %d)\n", count, c)
		msg += fmt.Sprintf("Calls made (%d total):\n", len(m.logCalls))
		for i, call := range m.logCalls {
			msg += fmt.Sprintf("  [%d] message=%+v\n", i, call.message)
		}
		panic(msg)
	}
}

func (m *MockLogger) Log(message string) () {
	for _, setup := range m.logSetups {
		if setup.message.Compare(message) {
			m.logCalls = append(m.logCalls, MockLoggerLogCall{
				message: message,
			})

			return 
		}
	}

	// No matching setup found, generate helpful error message
	msg := fmt.Sprintf("no mock setup found for MockLogger.Log with the provided arguments: message=%+v\n", message)
	msg += fmt.Sprintf("\nSetups registered (%d total):\n", len(m.logSetups))
	for i, setup := range m.logSetups {
		msg += fmt.Sprintf("  [%d] message=%s\n", i, setup.message)
	}
	if len(m.logSetups) == 0 {
		msg += "  (no setups registered)\n"
	}
	panic(msg)
}

type MockLoggerLogWithLevelSetup struct {
	level mq.Input[string]
	message mq.Input[string]
}

type MockLoggerLogWithLevelCall struct {
	level string
	message string
}

// SetupLogWithLevel configures the mock to return specific outputs when LogWithLevel is called with matching inputs.
func (m *MockLogger) SetupLogWithLevel(level mq.Input[string], message mq.Input[string]) {
	m.logWithLevelSetups = append(m.logWithLevelSetups, MockLoggerLogWithLevelSetup{
		level: level,
		message: message,
	})
}

// VerifyLogWithLevel checks that LogWithLevel was called the expected number of times with matching inputs.
func (m *MockLogger) VerifyLogWithLevel(count mq.Count, level mq.Input[string], message mq.Input[string]) {
	c := 0

	for _, call := range m.logWithLevelCalls {
		if level.Compare(call.level) && message.Compare(call.message) {
			c++
		}
	}

	if !count.ShouldPass(c) {
		msg := fmt.Sprintf("mock verification failed for Logger.LogWithLevel: expected %s (count: %d)\n", count, c)
		msg += fmt.Sprintf("Calls made (%d total):\n", len(m.logWithLevelCalls))
		for i, call := range m.logWithLevelCalls {
			msg += fmt.Sprintf("  [%d] level=%+v, message=%+v\n", i, call.level, call.message)
		}
		panic(msg)
	}
}

func (m *MockLogger) LogWithLevel(level string, message string) () {
	for _, setup := range m.logWithLevelSetups {
		if setup.level.Compare(level) && setup.message.Compare(message) {
			m.logWithLevelCalls = append(m.logWithLevelCalls, MockLoggerLogWithLevelCall{
				level: level,
				message: message,
			})

			return 
		}
	}

	// No matching setup found, generate helpful error message
	msg := fmt.Sprintf("no mock setup found for MockLogger.LogWithLevel with the provided arguments: level=%+v, message=%+v\n", level, message)
	msg += fmt.Sprintf("\nSetups registered (%d total):\n", len(m.logWithLevelSetups))
	for i, setup := range m.logWithLevelSetups {
		msg += fmt.Sprintf("  [%d] level=%s, message=%s\n", i, setup.level, setup.message)
	}
	if len(m.logWithLevelSetups) == 0 {
		msg += "  (no setups registered)\n"
	}
	panic(msg)
}

