// This file was automatically generated by mq. DO NOT EDIT.
package noparameters

import (
	"fmt"
	"github.com/lukejoshuapark/mq"
)

// MockStatusProvider is a mock implementation of the StatusProvider interface.
type MockStatusProvider struct {
	getStatusSetups []MockStatusProviderGetStatusSetup
	getStatusCalls []MockStatusProviderGetStatusCall
	isReadySetups []MockStatusProviderIsReadySetup
	isReadyCalls []MockStatusProviderIsReadyCall
	refreshSetups []MockStatusProviderRefreshSetup
	refreshCalls []MockStatusProviderRefreshCall
}

var _ StatusProvider = &MockStatusProvider{}

// NewMockStatusProvider creates a new instance of MockStatusProvider.
func NewMockStatusProvider() *MockStatusProvider {
	return &MockStatusProvider{}
}

type MockStatusProviderGetStatusSetup struct {
	output0 mq.Output[string]
}

type MockStatusProviderGetStatusCall struct {
}

// SetupGetStatus configures the mock to return specific outputs when GetStatus is called with matching inputs.
func (m *MockStatusProvider) SetupGetStatus(output0 mq.Output[string]) {
	m.getStatusSetups = append(m.getStatusSetups, MockStatusProviderGetStatusSetup{
		output0: output0,
	})
}

// VerifyGetStatus checks that GetStatus was called the expected number of times with matching inputs.
func (m *MockStatusProvider) VerifyGetStatus(count mq.Count) {
	c := 0

	for _, call := range m.getStatusCalls {
		c++
	}

	if !count.ShouldPass(c) {
		panic(fmt.Sprintf("mock verification failed for StatusProvider.GetStatus: expected count not met (actual: %d)", c))
	}
}

func (m *MockStatusProvider) GetStatus() string {
	for _, setup := range m.getStatusSetups {
			m.getStatusCalls = append(m.getStatusCalls, MockStatusProviderGetStatusCall{
			})

			return setup.output0.Value()
	}

	panic("no mock setup found for MockStatusProvider.GetStatus with the provided arguments")
}

type MockStatusProviderIsReadySetup struct {
	output0 mq.Output[bool]
	output1 mq.Output[error]
}

type MockStatusProviderIsReadyCall struct {
}

// SetupIsReady configures the mock to return specific outputs when IsReady is called with matching inputs.
func (m *MockStatusProvider) SetupIsReady(output0 mq.Output[bool], output1 mq.Output[error]) {
	m.isReadySetups = append(m.isReadySetups, MockStatusProviderIsReadySetup{
		output0: output0,
		output1: output1,
	})
}

// VerifyIsReady checks that IsReady was called the expected number of times with matching inputs.
func (m *MockStatusProvider) VerifyIsReady(count mq.Count) {
	c := 0

	for _, call := range m.isReadyCalls {
		c++
	}

	if !count.ShouldPass(c) {
		panic(fmt.Sprintf("mock verification failed for StatusProvider.IsReady: expected count not met (actual: %d)", c))
	}
}

func (m *MockStatusProvider) IsReady() (bool, error) {
	for _, setup := range m.isReadySetups {
			m.isReadyCalls = append(m.isReadyCalls, MockStatusProviderIsReadyCall{
			})

			return setup.output0.Value(), setup.output1.Value()
	}

	panic("no mock setup found for MockStatusProvider.IsReady with the provided arguments")
}

type MockStatusProviderRefreshSetup struct {
}

type MockStatusProviderRefreshCall struct {
}

// SetupRefresh configures the mock to return specific outputs when Refresh is called with matching inputs.
func (m *MockStatusProvider) SetupRefresh() {
	m.refreshSetups = append(m.refreshSetups, MockStatusProviderRefreshSetup{
	})
}

// VerifyRefresh checks that Refresh was called the expected number of times with matching inputs.
func (m *MockStatusProvider) VerifyRefresh(count mq.Count) {
	c := 0

	for _, call := range m.refreshCalls {
		c++
	}

	if !count.ShouldPass(c) {
		panic(fmt.Sprintf("mock verification failed for StatusProvider.Refresh: expected count not met (actual: %d)", c))
	}
}

func (m *MockStatusProvider) Refresh() () {
	for _, setup := range m.refreshSetups {
			m.refreshCalls = append(m.refreshCalls, MockStatusProviderRefreshCall{
			})

			return 
	}

	panic("no mock setup found for MockStatusProvider.Refresh with the provided arguments")
}

