// This file was automatically generated by mq. DO NOT EDIT.
package noparameters

import (
	"fmt"
	"github.com/lukejoshuapark/mq"
)

// MockStatusProvider is a mock implementation of the StatusProvider interface.
type MockStatusProvider struct {
	getStatusSetups []MockStatusProviderGetStatusSetup
	getStatusCalls []MockStatusProviderGetStatusCall
	isReadySetups []MockStatusProviderIsReadySetup
	isReadyCalls []MockStatusProviderIsReadyCall
	refreshSetups []MockStatusProviderRefreshSetup
	refreshCalls []MockStatusProviderRefreshCall
}

// NewMockStatusProvider creates a new instance of MockStatusProvider.
func NewMockStatusProvider() *MockStatusProvider {
	return &MockStatusProvider{}
}

type MockStatusProviderGetStatusSetup struct {
	output0 mq.Output[string]
}

type MockStatusProviderGetStatusCall struct {
}

// SetupGetStatus configures the mock to return specific outputs when GetStatus is called with matching inputs.
func (m *MockStatusProvider) SetupGetStatus(output0 mq.Output[string]) {
	m.getStatusSetups = append(m.getStatusSetups, MockStatusProviderGetStatusSetup{
		output0: output0,
	})
}

// VerifyGetStatus checks that GetStatus was called the expected number of times with matching inputs.
func (m *MockStatusProvider) VerifyGetStatus(count mq.Count) {
	c := len(m.getStatusCalls)

	if !count.ShouldPass(c) {
		msg := fmt.Sprintf("mock verification failed for StatusProvider.GetStatus: expected %s (count: %d)\n", count, c)
		msg += fmt.Sprintf("Calls made (%d total):\n", len(m.getStatusCalls))
		for i := range m.getStatusCalls {
			msg += fmt.Sprintf("  [%d] (no parameters)\n", i)
		}
		panic(msg)
	}
}

func (m *MockStatusProvider) GetStatus() string {
	if len(m.getStatusSetups) > 0 {
		m.getStatusCalls = append(m.getStatusCalls, MockStatusProviderGetStatusCall{})

		return m.getStatusSetups[0].output0.Value()
	}

	// No matching setup found, generate helpful error message
	msg := "no mock setup found for MockStatusProvider.GetStatus\n"
	msg += fmt.Sprintf("\nSetups registered (%d total):\n", len(m.getStatusSetups))
	for i := range m.getStatusSetups {
		msg += fmt.Sprintf("  [%d] (no parameters)\n", i)
	}
	if len(m.getStatusSetups) == 0 {
		msg += "  (no setups registered)\n"
	}
	panic(msg)
}

type MockStatusProviderIsReadySetup struct {
	output0 mq.Output[bool]
	output1 mq.Output[error]
}

type MockStatusProviderIsReadyCall struct {
}

// SetupIsReady configures the mock to return specific outputs when IsReady is called with matching inputs.
func (m *MockStatusProvider) SetupIsReady(output0 mq.Output[bool], output1 mq.Output[error]) {
	m.isReadySetups = append(m.isReadySetups, MockStatusProviderIsReadySetup{
		output0: output0,
		output1: output1,
	})
}

// VerifyIsReady checks that IsReady was called the expected number of times with matching inputs.
func (m *MockStatusProvider) VerifyIsReady(count mq.Count) {
	c := len(m.isReadyCalls)

	if !count.ShouldPass(c) {
		msg := fmt.Sprintf("mock verification failed for StatusProvider.IsReady: expected %s (count: %d)\n", count, c)
		msg += fmt.Sprintf("Calls made (%d total):\n", len(m.isReadyCalls))
		for i := range m.isReadyCalls {
			msg += fmt.Sprintf("  [%d] (no parameters)\n", i)
		}
		panic(msg)
	}
}

func (m *MockStatusProvider) IsReady() (bool, error) {
	if len(m.isReadySetups) > 0 {
		m.isReadyCalls = append(m.isReadyCalls, MockStatusProviderIsReadyCall{})

		return m.isReadySetups[0].output0.Value(), m.isReadySetups[0].output1.Value()
	}

	// No matching setup found, generate helpful error message
	msg := "no mock setup found for MockStatusProvider.IsReady\n"
	msg += fmt.Sprintf("\nSetups registered (%d total):\n", len(m.isReadySetups))
	for i := range m.isReadySetups {
		msg += fmt.Sprintf("  [%d] (no parameters)\n", i)
	}
	if len(m.isReadySetups) == 0 {
		msg += "  (no setups registered)\n"
	}
	panic(msg)
}

type MockStatusProviderRefreshSetup struct {
}

type MockStatusProviderRefreshCall struct {
}

// SetupRefresh configures the mock to return specific outputs when Refresh is called with matching inputs.
func (m *MockStatusProvider) SetupRefresh() {
	m.refreshSetups = append(m.refreshSetups, MockStatusProviderRefreshSetup{
	})
}

// VerifyRefresh checks that Refresh was called the expected number of times with matching inputs.
func (m *MockStatusProvider) VerifyRefresh(count mq.Count) {
	c := len(m.refreshCalls)

	if !count.ShouldPass(c) {
		msg := fmt.Sprintf("mock verification failed for StatusProvider.Refresh: expected %s (count: %d)\n", count, c)
		msg += fmt.Sprintf("Calls made (%d total):\n", len(m.refreshCalls))
		for i := range m.refreshCalls {
			msg += fmt.Sprintf("  [%d] (no parameters)\n", i)
		}
		panic(msg)
	}
}

func (m *MockStatusProvider) Refresh() () {
	if len(m.refreshSetups) > 0 {
		m.refreshCalls = append(m.refreshCalls, MockStatusProviderRefreshCall{})

		return 
	}

	// No matching setup found, generate helpful error message
	msg := "no mock setup found for MockStatusProvider.Refresh\n"
	msg += fmt.Sprintf("\nSetups registered (%d total):\n", len(m.refreshSetups))
	for i := range m.refreshSetups {
		msg += fmt.Sprintf("  [%d] (no parameters)\n", i)
	}
	if len(m.refreshSetups) == 0 {
		msg += "  (no setups registered)\n"
	}
	panic(msg)
}

