// This file was automatically generated by mq. DO NOT EDIT.
package genericinterface

import (
	"context"
	"fmt"

	"github.com/lukejoshuapark/mq"
)

// MockRepository is a mock implementation of the Repository interface.
type MockRepository[T any] struct {
	getSetups  []MockRepositoryGetSetup[T]
	getCalls   []MockRepositoryGetCall[T]
	saveSetups []MockRepositorySaveSetup[T]
	saveCalls  []MockRepositorySaveCall[T]
	listSetups []MockRepositoryListSetup[T]
	listCalls  []MockRepositoryListCall[T]
}

// NewMockRepository creates a new instance of MockRepository.
func NewMockRepository[T any]() *MockRepository[T] {
	return &MockRepository[T]{}
}

type MockRepositoryGetSetup[T any] struct {
	ctx     mq.Input[context.Context]
	id      mq.Input[string]
	output0 mq.Output[T]
	output1 mq.Output[error]
}

type MockRepositoryGetCall[T any] struct {
	ctx context.Context
	id  string
}

// SetupGet configures the mock to return specific outputs when Get is called with matching inputs.
func (m *MockRepository[T]) SetupGet(ctx mq.Input[context.Context], id mq.Input[string], output0 mq.Output[T], output1 mq.Output[error]) {
	m.getSetups = append(m.getSetups, MockRepositoryGetSetup[T]{
		ctx:     ctx,
		id:      id,
		output0: output0,
		output1: output1,
	})
}

// VerifyGet checks that Get was called the expected number of times with matching inputs.
func (m *MockRepository[T]) VerifyGet(count mq.Count, ctx mq.Input[context.Context], id mq.Input[string]) {
	c := 0

	for _, call := range m.getCalls {
		if ctx.Compare(call.ctx) && id.Compare(call.id) {
			c++
		}
	}

	if !count.ShouldPass(c) {
		panic(fmt.Sprintf("mock verification failed for Repository.Get: expected count not met (actual: %d)", c))
	}
}

func (m *MockRepository[T]) Get(ctx context.Context, id string) (T, error) {
	for _, setup := range m.getSetups {
		if setup.ctx.Compare(ctx) && setup.id.Compare(id) {
			m.getCalls = append(m.getCalls, MockRepositoryGetCall[T]{
				ctx: ctx,
				id:  id,
			})

			return setup.output0.Value(), setup.output1.Value()
		}
	}

	panic("no mock setup found for MockRepository.Get with the provided arguments")
}

type MockRepositorySaveSetup[T any] struct {
	ctx     mq.Input[context.Context]
	item    mq.Input[T]
	output0 mq.Output[error]
}

type MockRepositorySaveCall[T any] struct {
	ctx  context.Context
	item T
}

// SetupSave configures the mock to return specific outputs when Save is called with matching inputs.
func (m *MockRepository[T]) SetupSave(ctx mq.Input[context.Context], item mq.Input[T], output0 mq.Output[error]) {
	m.saveSetups = append(m.saveSetups, MockRepositorySaveSetup[T]{
		ctx:     ctx,
		item:    item,
		output0: output0,
	})
}

// VerifySave checks that Save was called the expected number of times with matching inputs.
func (m *MockRepository[T]) VerifySave(count mq.Count, ctx mq.Input[context.Context], item mq.Input[T]) {
	c := 0

	for _, call := range m.saveCalls {
		if ctx.Compare(call.ctx) && item.Compare(call.item) {
			c++
		}
	}

	if !count.ShouldPass(c) {
		panic(fmt.Sprintf("mock verification failed for Repository.Save: expected count not met (actual: %d)", c))
	}
}

func (m *MockRepository[T]) Save(ctx context.Context, item T) error {
	for _, setup := range m.saveSetups {
		if setup.ctx.Compare(ctx) && setup.item.Compare(item) {
			m.saveCalls = append(m.saveCalls, MockRepositorySaveCall[T]{
				ctx:  ctx,
				item: item,
			})

			return setup.output0.Value()
		}
	}

	panic("no mock setup found for MockRepository.Save with the provided arguments")
}

type MockRepositoryListSetup[T any] struct {
	ctx     mq.Input[context.Context]
	output0 mq.Output[[]T]
	output1 mq.Output[error]
}

type MockRepositoryListCall[T any] struct {
	ctx context.Context
}

// SetupList configures the mock to return specific outputs when List is called with matching inputs.
func (m *MockRepository[T]) SetupList(ctx mq.Input[context.Context], output0 mq.Output[[]T], output1 mq.Output[error]) {
	m.listSetups = append(m.listSetups, MockRepositoryListSetup[T]{
		ctx:     ctx,
		output0: output0,
		output1: output1,
	})
}

// VerifyList checks that List was called the expected number of times with matching inputs.
func (m *MockRepository[T]) VerifyList(count mq.Count, ctx mq.Input[context.Context]) {
	c := 0

	for _, call := range m.listCalls {
		if ctx.Compare(call.ctx) {
			c++
		}
	}

	if !count.ShouldPass(c) {
		panic(fmt.Sprintf("mock verification failed for Repository.List: expected count not met (actual: %d)", c))
	}
}

func (m *MockRepository[T]) List(ctx context.Context) ([]T, error) {
	for _, setup := range m.listSetups {
		if setup.ctx.Compare(ctx) {
			m.listCalls = append(m.listCalls, MockRepositoryListCall[T]{
				ctx: ctx,
			})

			return setup.output0.Value(), setup.output1.Value()
		}
	}

	panic("no mock setup found for MockRepository.List with the provided arguments")
}

// MockCache is a mock implementation of the Cache interface.
type MockCache[K comparable, V any] struct {
	getSetups    []MockCacheGetSetup[K, V]
	getCalls     []MockCacheGetCall[K, V]
	setSetups    []MockCacheSetSetup[K, V]
	setCalls     []MockCacheSetCall[K, V]
	deleteSetups []MockCacheDeleteSetup[K, V]
	deleteCalls  []MockCacheDeleteCall[K, V]
}

// NewMockCache creates a new instance of MockCache.
func NewMockCache[K comparable, V any]() *MockCache[K, V] {
	return &MockCache[K, V]{}
}

type MockCacheGetSetup[K comparable, V any] struct {
	key     mq.Input[K]
	output0 mq.Output[V]
	output1 mq.Output[bool]
}

type MockCacheGetCall[K comparable, V any] struct {
	key K
}

// SetupGet configures the mock to return specific outputs when Get is called with matching inputs.
func (m *MockCache[K, V]) SetupGet(key mq.Input[K], output0 mq.Output[V], output1 mq.Output[bool]) {
	m.getSetups = append(m.getSetups, MockCacheGetSetup[K, V]{
		key:     key,
		output0: output0,
		output1: output1,
	})
}

// VerifyGet checks that Get was called the expected number of times with matching inputs.
func (m *MockCache[K, V]) VerifyGet(count mq.Count, key mq.Input[K]) {
	c := 0

	for _, call := range m.getCalls {
		if key.Compare(call.key) {
			c++
		}
	}

	if !count.ShouldPass(c) {
		panic(fmt.Sprintf("mock verification failed for Cache.Get: expected count not met (actual: %d)", c))
	}
}

func (m *MockCache[K, V]) Get(key K) (V, bool) {
	for _, setup := range m.getSetups {
		if setup.key.Compare(key) {
			m.getCalls = append(m.getCalls, MockCacheGetCall[K, V]{
				key: key,
			})

			return setup.output0.Value(), setup.output1.Value()
		}
	}

	panic("no mock setup found for MockCache.Get with the provided arguments")
}

type MockCacheSetSetup[K comparable, V any] struct {
	key   mq.Input[K]
	value mq.Input[V]
}

type MockCacheSetCall[K comparable, V any] struct {
	key   K
	value V
}

// SetupSet configures the mock to return specific outputs when Set is called with matching inputs.
func (m *MockCache[K, V]) SetupSet(key mq.Input[K], value mq.Input[V]) {
	m.setSetups = append(m.setSetups, MockCacheSetSetup[K, V]{
		key:   key,
		value: value,
	})
}

// VerifySet checks that Set was called the expected number of times with matching inputs.
func (m *MockCache[K, V]) VerifySet(count mq.Count, key mq.Input[K], value mq.Input[V]) {
	c := 0

	for _, call := range m.setCalls {
		if key.Compare(call.key) && value.Compare(call.value) {
			c++
		}
	}

	if !count.ShouldPass(c) {
		panic(fmt.Sprintf("mock verification failed for Cache.Set: expected count not met (actual: %d)", c))
	}
}

func (m *MockCache[K, V]) Set(key K, value V) {
	for _, setup := range m.setSetups {
		if setup.key.Compare(key) && setup.value.Compare(value) {
			m.setCalls = append(m.setCalls, MockCacheSetCall[K, V]{
				key:   key,
				value: value,
			})

			return
		}
	}

	panic("no mock setup found for MockCache.Set with the provided arguments")
}

type MockCacheDeleteSetup[K comparable, V any] struct {
	key     mq.Input[K]
	output0 mq.Output[bool]
}

type MockCacheDeleteCall[K comparable, V any] struct {
	key K
}

// SetupDelete configures the mock to return specific outputs when Delete is called with matching inputs.
func (m *MockCache[K, V]) SetupDelete(key mq.Input[K], output0 mq.Output[bool]) {
	m.deleteSetups = append(m.deleteSetups, MockCacheDeleteSetup[K, V]{
		key:     key,
		output0: output0,
	})
}

// VerifyDelete checks that Delete was called the expected number of times with matching inputs.
func (m *MockCache[K, V]) VerifyDelete(count mq.Count, key mq.Input[K]) {
	c := 0

	for _, call := range m.deleteCalls {
		if key.Compare(call.key) {
			c++
		}
	}

	if !count.ShouldPass(c) {
		panic(fmt.Sprintf("mock verification failed for Cache.Delete: expected count not met (actual: %d)", c))
	}
}

func (m *MockCache[K, V]) Delete(key K) bool {
	for _, setup := range m.deleteSetups {
		if setup.key.Compare(key) {
			m.deleteCalls = append(m.deleteCalls, MockCacheDeleteCall[K, V]{
				key: key,
			})

			return setup.output0.Value()
		}
	}

	panic("no mock setup found for MockCache.Delete with the provided arguments")
}
