// This file was automatically generated by mq. DO NOT EDIT.
package multiinterface

import (
	"fmt"
	"github.com/lukejoshuapark/mq"
)

// MockReader is a mock implementation of the Reader interface.
type MockReader struct {
	readSetups []MockReaderReadSetup
	readCalls []MockReaderReadCall
	existsSetups []MockReaderExistsSetup
	existsCalls []MockReaderExistsCall
}

// NewMockReader creates a new instance of MockReader.
func NewMockReader() *MockReader {
	return &MockReader{}
}

type MockReaderReadSetup struct {
	key mq.Input[string]
	output0 mq.Output[string]
	output1 mq.Output[error]
}

type MockReaderReadCall struct {
	key string
}

// SetupRead configures the mock to return specific outputs when Read is called with matching inputs.
func (m *MockReader) SetupRead(key mq.Input[string], output0 mq.Output[string], output1 mq.Output[error]) {
	m.readSetups = append(m.readSetups, MockReaderReadSetup{
		key: key,
		output0: output0,
		output1: output1,
	})
}

// VerifyRead checks that Read was called the expected number of times with matching inputs.
func (m *MockReader) VerifyRead(count mq.Count, key mq.Input[string]) {
	c := 0

	for _, call := range m.readCalls {
		if key.Compare(call.key) {
			c++
		}
	}

	if !count.ShouldPass(c) {
		msg := fmt.Sprintf("mock verification failed for Reader.Read: expected %s (count: %d)\n", count, c)
		msg += fmt.Sprintf("Calls made (%d total):\n", len(m.readCalls))
		for i, call := range m.readCalls {
			msg += fmt.Sprintf("  [%d] key=%+v\n", i, call.key)
		}
		panic(msg)
	}
}

func (m *MockReader) Read(key string) (string, error) {
	for _, setup := range m.readSetups {
		if setup.key.Compare(key) {
			m.readCalls = append(m.readCalls, MockReaderReadCall{
				key: key,
			})

			return setup.output0.Value(), setup.output1.Value()
		}
	}

	// No matching setup found, generate helpful error message
	msg := fmt.Sprintf("no mock setup found for MockReader.Read with the provided arguments: key=%+v\n", key)
	msg += fmt.Sprintf("\nSetups registered (%d total):\n", len(m.readSetups))
	for i, setup := range m.readSetups {
		msg += fmt.Sprintf("  [%d] key=%s\n", i, setup.key)
	}
	if len(m.readSetups) == 0 {
		msg += "  (no setups registered)\n"
	}
	panic(msg)
}

type MockReaderExistsSetup struct {
	key mq.Input[string]
	output0 mq.Output[bool]
}

type MockReaderExistsCall struct {
	key string
}

// SetupExists configures the mock to return specific outputs when Exists is called with matching inputs.
func (m *MockReader) SetupExists(key mq.Input[string], output0 mq.Output[bool]) {
	m.existsSetups = append(m.existsSetups, MockReaderExistsSetup{
		key: key,
		output0: output0,
	})
}

// VerifyExists checks that Exists was called the expected number of times with matching inputs.
func (m *MockReader) VerifyExists(count mq.Count, key mq.Input[string]) {
	c := 0

	for _, call := range m.existsCalls {
		if key.Compare(call.key) {
			c++
		}
	}

	if !count.ShouldPass(c) {
		msg := fmt.Sprintf("mock verification failed for Reader.Exists: expected %s (count: %d)\n", count, c)
		msg += fmt.Sprintf("Calls made (%d total):\n", len(m.existsCalls))
		for i, call := range m.existsCalls {
			msg += fmt.Sprintf("  [%d] key=%+v\n", i, call.key)
		}
		panic(msg)
	}
}

func (m *MockReader) Exists(key string) bool {
	for _, setup := range m.existsSetups {
		if setup.key.Compare(key) {
			m.existsCalls = append(m.existsCalls, MockReaderExistsCall{
				key: key,
			})

			return setup.output0.Value()
		}
	}

	// No matching setup found, generate helpful error message
	msg := fmt.Sprintf("no mock setup found for MockReader.Exists with the provided arguments: key=%+v\n", key)
	msg += fmt.Sprintf("\nSetups registered (%d total):\n", len(m.existsSetups))
	for i, setup := range m.existsSetups {
		msg += fmt.Sprintf("  [%d] key=%s\n", i, setup.key)
	}
	if len(m.existsSetups) == 0 {
		msg += "  (no setups registered)\n"
	}
	panic(msg)
}

// MockWriter is a mock implementation of the Writer interface.
type MockWriter struct {
	writeSetups []MockWriterWriteSetup
	writeCalls []MockWriterWriteCall
	deleteSetups []MockWriterDeleteSetup
	deleteCalls []MockWriterDeleteCall
}

// NewMockWriter creates a new instance of MockWriter.
func NewMockWriter() *MockWriter {
	return &MockWriter{}
}

type MockWriterWriteSetup struct {
	key mq.Input[string]
	value mq.Input[string]
	output0 mq.Output[error]
}

type MockWriterWriteCall struct {
	key string
	value string
}

// SetupWrite configures the mock to return specific outputs when Write is called with matching inputs.
func (m *MockWriter) SetupWrite(key mq.Input[string], value mq.Input[string], output0 mq.Output[error]) {
	m.writeSetups = append(m.writeSetups, MockWriterWriteSetup{
		key: key,
		value: value,
		output0: output0,
	})
}

// VerifyWrite checks that Write was called the expected number of times with matching inputs.
func (m *MockWriter) VerifyWrite(count mq.Count, key mq.Input[string], value mq.Input[string]) {
	c := 0

	for _, call := range m.writeCalls {
		if key.Compare(call.key) && value.Compare(call.value) {
			c++
		}
	}

	if !count.ShouldPass(c) {
		msg := fmt.Sprintf("mock verification failed for Writer.Write: expected %s (count: %d)\n", count, c)
		msg += fmt.Sprintf("Calls made (%d total):\n", len(m.writeCalls))
		for i, call := range m.writeCalls {
			msg += fmt.Sprintf("  [%d] key=%+v, value=%+v\n", i, call.key, call.value)
		}
		panic(msg)
	}
}

func (m *MockWriter) Write(key string, value string) error {
	for _, setup := range m.writeSetups {
		if setup.key.Compare(key) && setup.value.Compare(value) {
			m.writeCalls = append(m.writeCalls, MockWriterWriteCall{
				key: key,
				value: value,
			})

			return setup.output0.Value()
		}
	}

	// No matching setup found, generate helpful error message
	msg := fmt.Sprintf("no mock setup found for MockWriter.Write with the provided arguments: key=%+v, value=%+v\n", key, value)
	msg += fmt.Sprintf("\nSetups registered (%d total):\n", len(m.writeSetups))
	for i, setup := range m.writeSetups {
		msg += fmt.Sprintf("  [%d] key=%s, value=%s\n", i, setup.key, setup.value)
	}
	if len(m.writeSetups) == 0 {
		msg += "  (no setups registered)\n"
	}
	panic(msg)
}

type MockWriterDeleteSetup struct {
	key mq.Input[string]
	output0 mq.Output[error]
}

type MockWriterDeleteCall struct {
	key string
}

// SetupDelete configures the mock to return specific outputs when Delete is called with matching inputs.
func (m *MockWriter) SetupDelete(key mq.Input[string], output0 mq.Output[error]) {
	m.deleteSetups = append(m.deleteSetups, MockWriterDeleteSetup{
		key: key,
		output0: output0,
	})
}

// VerifyDelete checks that Delete was called the expected number of times with matching inputs.
func (m *MockWriter) VerifyDelete(count mq.Count, key mq.Input[string]) {
	c := 0

	for _, call := range m.deleteCalls {
		if key.Compare(call.key) {
			c++
		}
	}

	if !count.ShouldPass(c) {
		msg := fmt.Sprintf("mock verification failed for Writer.Delete: expected %s (count: %d)\n", count, c)
		msg += fmt.Sprintf("Calls made (%d total):\n", len(m.deleteCalls))
		for i, call := range m.deleteCalls {
			msg += fmt.Sprintf("  [%d] key=%+v\n", i, call.key)
		}
		panic(msg)
	}
}

func (m *MockWriter) Delete(key string) error {
	for _, setup := range m.deleteSetups {
		if setup.key.Compare(key) {
			m.deleteCalls = append(m.deleteCalls, MockWriterDeleteCall{
				key: key,
			})

			return setup.output0.Value()
		}
	}

	// No matching setup found, generate helpful error message
	msg := fmt.Sprintf("no mock setup found for MockWriter.Delete with the provided arguments: key=%+v\n", key)
	msg += fmt.Sprintf("\nSetups registered (%d total):\n", len(m.deleteSetups))
	for i, setup := range m.deleteSetups {
		msg += fmt.Sprintf("  [%d] key=%s\n", i, setup.key)
	}
	if len(m.deleteSetups) == 0 {
		msg += "  (no setups registered)\n"
	}
	panic(msg)
}

