// This file was automatically generated by mq. DO NOT EDIT.
package channels

import (
	"fmt"
	"github.com/lukejoshuapark/mq"
)

// MockEventBus is a mock implementation of the EventBus interface.
type MockEventBus struct {
	subscribeSetups []MockEventBusSubscribeSetup
	subscribeCalls []MockEventBusSubscribeCall
	publishSetups []MockEventBusPublishSetup
	publishCalls []MockEventBusPublishCall
	streamSetups []MockEventBusStreamSetup
	streamCalls []MockEventBusStreamCall
	closeSetups []MockEventBusCloseSetup
	closeCalls []MockEventBusCloseCall
}

// NewMockEventBus creates a new instance of MockEventBus.
func NewMockEventBus() *MockEventBus {
	return &MockEventBus{}
}

type MockEventBusSubscribeSetup struct {
	output0 mq.Output[<-chan Event]
}

type MockEventBusSubscribeCall struct {
}

// SetupSubscribe configures the mock to return specific outputs when Subscribe is called with matching inputs.
func (m *MockEventBus) SetupSubscribe(output0 mq.Output[<-chan Event]) {
	m.subscribeSetups = append(m.subscribeSetups, MockEventBusSubscribeSetup{
		output0: output0,
	})
}

// VerifySubscribe checks that Subscribe was called the expected number of times with matching inputs.
func (m *MockEventBus) VerifySubscribe(count mq.Count) {
	c := len(m.subscribeCalls)

	if !count.ShouldPass(c) {
		msg := fmt.Sprintf("mock verification failed for EventBus.Subscribe: expected %s (count: %d)\n", count, c)
		msg += fmt.Sprintf("Calls made (%d total):\n", len(m.subscribeCalls))
		for i := range m.subscribeCalls {
			msg += fmt.Sprintf("  [%d] (no parameters)\n", i)
		}
		panic(msg)
	}
}

func (m *MockEventBus) Subscribe() <-chan Event {
	if len(m.subscribeSetups) > 0 {
		m.subscribeCalls = append(m.subscribeCalls, MockEventBusSubscribeCall{})

		return m.subscribeSetups[0].output0.Value()
	}

	// No matching setup found, generate helpful error message
	msg := "no mock setup found for MockEventBus.Subscribe\n"
	msg += fmt.Sprintf("\nSetups registered (%d total):\n", len(m.subscribeSetups))
	for i := range m.subscribeSetups {
		msg += fmt.Sprintf("  [%d] (no parameters)\n", i)
	}
	if len(m.subscribeSetups) == 0 {
		msg += "  (no setups registered)\n"
	}
	panic(msg)
}

type MockEventBusPublishSetup struct {
	events mq.Input[chan<- Event]
	output0 mq.Output[error]
}

type MockEventBusPublishCall struct {
	events chan<- Event
}

// SetupPublish configures the mock to return specific outputs when Publish is called with matching inputs.
func (m *MockEventBus) SetupPublish(events mq.Input[chan<- Event], output0 mq.Output[error]) {
	m.publishSetups = append(m.publishSetups, MockEventBusPublishSetup{
		events: events,
		output0: output0,
	})
}

// VerifyPublish checks that Publish was called the expected number of times with matching inputs.
func (m *MockEventBus) VerifyPublish(count mq.Count, events mq.Input[chan<- Event]) {
	c := 0

	for _, call := range m.publishCalls {
		if events.Compare(call.events) {
			c++
		}
	}

	if !count.ShouldPass(c) {
		msg := fmt.Sprintf("mock verification failed for EventBus.Publish: expected %s (count: %d)\n", count, c)
		msg += fmt.Sprintf("Calls made (%d total):\n", len(m.publishCalls))
		for i, call := range m.publishCalls {
			msg += fmt.Sprintf("  [%d] events=%+v\n", i, call.events)
		}
		panic(msg)
	}
}

func (m *MockEventBus) Publish(events chan<- Event) error {
	for _, setup := range m.publishSetups {
		if setup.events.Compare(events) {
			m.publishCalls = append(m.publishCalls, MockEventBusPublishCall{
				events: events,
			})

			return setup.output0.Value()
		}
	}

	// No matching setup found, generate helpful error message
	msg := fmt.Sprintf("no mock setup found for MockEventBus.Publish with the provided arguments: events=%+v\n", events)
	msg += fmt.Sprintf("\nSetups registered (%d total):\n", len(m.publishSetups))
	for i, setup := range m.publishSetups {
		msg += fmt.Sprintf("  [%d] events=%s\n", i, setup.events)
	}
	if len(m.publishSetups) == 0 {
		msg += "  (no setups registered)\n"
	}
	panic(msg)
}

type MockEventBusStreamSetup struct {
	output0 mq.Output[chan Event]
}

type MockEventBusStreamCall struct {
}

// SetupStream configures the mock to return specific outputs when Stream is called with matching inputs.
func (m *MockEventBus) SetupStream(output0 mq.Output[chan Event]) {
	m.streamSetups = append(m.streamSetups, MockEventBusStreamSetup{
		output0: output0,
	})
}

// VerifyStream checks that Stream was called the expected number of times with matching inputs.
func (m *MockEventBus) VerifyStream(count mq.Count) {
	c := len(m.streamCalls)

	if !count.ShouldPass(c) {
		msg := fmt.Sprintf("mock verification failed for EventBus.Stream: expected %s (count: %d)\n", count, c)
		msg += fmt.Sprintf("Calls made (%d total):\n", len(m.streamCalls))
		for i := range m.streamCalls {
			msg += fmt.Sprintf("  [%d] (no parameters)\n", i)
		}
		panic(msg)
	}
}

func (m *MockEventBus) Stream() chan Event {
	if len(m.streamSetups) > 0 {
		m.streamCalls = append(m.streamCalls, MockEventBusStreamCall{})

		return m.streamSetups[0].output0.Value()
	}

	// No matching setup found, generate helpful error message
	msg := "no mock setup found for MockEventBus.Stream\n"
	msg += fmt.Sprintf("\nSetups registered (%d total):\n", len(m.streamSetups))
	for i := range m.streamSetups {
		msg += fmt.Sprintf("  [%d] (no parameters)\n", i)
	}
	if len(m.streamSetups) == 0 {
		msg += "  (no setups registered)\n"
	}
	panic(msg)
}

type MockEventBusCloseSetup struct {
	done mq.Input[<-chan struct{}]
}

type MockEventBusCloseCall struct {
	done <-chan struct{}
}

// SetupClose configures the mock to return specific outputs when Close is called with matching inputs.
func (m *MockEventBus) SetupClose(done mq.Input[<-chan struct{}]) {
	m.closeSetups = append(m.closeSetups, MockEventBusCloseSetup{
		done: done,
	})
}

// VerifyClose checks that Close was called the expected number of times with matching inputs.
func (m *MockEventBus) VerifyClose(count mq.Count, done mq.Input[<-chan struct{}]) {
	c := 0

	for _, call := range m.closeCalls {
		if done.Compare(call.done) {
			c++
		}
	}

	if !count.ShouldPass(c) {
		msg := fmt.Sprintf("mock verification failed for EventBus.Close: expected %s (count: %d)\n", count, c)
		msg += fmt.Sprintf("Calls made (%d total):\n", len(m.closeCalls))
		for i, call := range m.closeCalls {
			msg += fmt.Sprintf("  [%d] done=%+v\n", i, call.done)
		}
		panic(msg)
	}
}

func (m *MockEventBus) Close(done <-chan struct{}) () {
	for _, setup := range m.closeSetups {
		if setup.done.Compare(done) {
			m.closeCalls = append(m.closeCalls, MockEventBusCloseCall{
				done: done,
			})

			return 
		}
	}

	// No matching setup found, generate helpful error message
	msg := fmt.Sprintf("no mock setup found for MockEventBus.Close with the provided arguments: done=%+v\n", done)
	msg += fmt.Sprintf("\nSetups registered (%d total):\n", len(m.closeSetups))
	for i, setup := range m.closeSetups {
		msg += fmt.Sprintf("  [%d] done=%s\n", i, setup.done)
	}
	if len(m.closeSetups) == 0 {
		msg += "  (no setups registered)\n"
	}
	panic(msg)
}

