package generate

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"slices"
	"strings"

	"github.com/lukejoshuapark/mq/cmd/mq/text/parse"
)

func Generate(file parse.File, fileName string) error {
	f, err := os.Create(fileName)
	if err != nil {
		return err
	}
	defer f.Close()

	w := bufio.NewWriter(f)
	defer w.Flush()

	if err := generateHeader(file, w); err != nil {
		return err
	}

	return nil
}

func generateHeader(file parse.File, w *bufio.Writer) error {
	if _, err := w.WriteString("// This file was automatically generated by mq. DO NOT EDIT.\n"); err != nil {
		return err
	}

	if _, err := w.WriteString("package " + file.PackageName + "\n\nimport (\n"); err != nil {
		return err
	}

	// Detect the mq module path from go.mod
	mqImportPath, err := getMqImportPath()
	if err != nil {
		// Fallback to hardcoded path if detection fails
		mqImportPath = "github.com/lukejoshuapark/mq"
	}

	file.Imports = append(file.Imports, "fmt")
	file.Imports = append(file.Imports, mqImportPath)
	slices.Sort(file.Imports)

	for _, imp := range file.Imports {
		if _, err := w.WriteString("\t\"" + imp + "\"\n"); err != nil {
			return err
		}
	}

	if _, err := w.WriteString(")\n\n"); err != nil {
		return err
	}

	return generateMockImplementations(file, w)
}

func generateMockImplementations(file parse.File, w *bufio.Writer) error {
	for _, intf := range file.Interfaces {
		if err := generateMockImplementation(intf, w); err != nil {
			return err
		}
	}

	return nil
}

func generateMockImplementation(intf parse.Interface, w *bufio.Writer) error {
	structName := "Mock" + intf.Name

	// Add documentation comment for the mock struct
	comment := fmt.Sprintf("// %s is a mock implementation of the %s interface.\n", structName, intf.Name)
	if _, err := w.WriteString(comment); err != nil {
		return err
	}

	if _, err := w.WriteString("type " + structName + intf.TypeParams + " struct {\n"); err != nil {
		return err
	}

	typeParamNames := getTypeParamNames(intf.TypeParams)

	for _, method := range intf.Methods {
		lowerCaseName := getStringWithFirstLetterLowercase(method.Name)
		if _, err := w.WriteString("\t" + lowerCaseName + "Setups []Mock" + intf.Name + method.Name + "Setup" + typeParamNames + "\n"); err != nil {
			return err
		}

		if _, err := w.WriteString("\t" + lowerCaseName + "Calls []Mock" + intf.Name + method.Name + "Call" + typeParamNames + "\n"); err != nil {
			return err
		}
	}

	if _, err := w.WriteString("}\n\n"); err != nil {
		return err
	}

	// Add documentation comment for the constructor
	comment = fmt.Sprintf("// New%s creates a new instance of %s.\n", structName, structName)
	if _, err := w.WriteString(comment); err != nil {
		return err
	}

	if _, err := w.WriteString("func New" + structName + intf.TypeParams + "() *" + structName + typeParamNames + " {\n\treturn &" + structName + typeParamNames + "{}\n}\n\n"); err != nil {
		return err
	}

	return generateMethods(structName, intf, w)
}

func generateMethods(structName string, intf parse.Interface, w *bufio.Writer) error {
	for _, method := range intf.Methods {
		if err := generateMethod(structName, intf.Name, intf.TypeParams, method, w); err != nil {
			return err
		}
	}

	return nil
}

func generateMethod(structName string, interfaceName string, interfaceTypeParams string, method parse.Method, w *bufio.Writer) error {
	typePrefix := structName + method.Name
	setupType := typePrefix + "Setup"
	callType := typePrefix + "Call"

	if _, err := w.WriteString("type " + setupType + interfaceTypeParams + " struct {\n"); err != nil {
		return err
	}

	for _, input := range method.Inputs {
		normalizedType := normalizeTypeForSetup(input.Type)
		if _, err := w.WriteString("\t" + input.Name + " mq.Input[" + normalizedType + "]\n"); err != nil {
			return err
		}
	}

	for i, output := range method.Outputs {
		outputName := getOutputName(output, i)
		if _, err := w.WriteString("\t" + outputName + " mq.Output[" + output.Type + "]\n"); err != nil {
			return err
		}
	}

	if _, err := w.WriteString("}\n\n"); err != nil {
		return err
	}

	if _, err := w.WriteString("type " + callType + interfaceTypeParams + " struct {\n"); err != nil {
		return err
	}

	for _, input := range method.Inputs {
		normalizedType := normalizeTypeForSetup(input.Type)
		if _, err := w.WriteString("\t" + input.Name + " " + normalizedType + "\n"); err != nil {
			return err
		}
	}

	if _, err := w.WriteString("}\n\n"); err != nil {
		return err
	}

	typeParamNames := getTypeParamNames(interfaceTypeParams)

	if err := generateSetupMethod(structName, interfaceTypeParams, typeParamNames, method, w); err != nil {
		return err
	}

	if err := generateVerifyMethod(structName, interfaceName, interfaceTypeParams, typeParamNames, method, w); err != nil {
		return err
	}

	if err := generateActualMethod(structName, interfaceTypeParams, typeParamNames, method, w); err != nil {
		return err
	}

	return nil
}

func generateSetupMethod(structName string, interfaceTypeParams string, typeParamNames string, method parse.Method, w *bufio.Writer) error {
	// Add documentation comment
	comment := fmt.Sprintf("// Setup%s configures the mock to return specific outputs when %s is called with matching inputs.\n", method.Name, method.Name)
	if _, err := w.WriteString(comment); err != nil {
		return err
	}

	if _, err := w.WriteString("func (m *" + structName + typeParamNames + ") Setup" + method.Name + "("); err != nil {
		return err
	}

	for i, input := range method.Inputs {
		if i != 0 {
			if _, err := w.WriteString(", "); err != nil {
				return err
			}
		}

		normalizedType := normalizeTypeForSetup(input.Type)
		if _, err := w.WriteString(input.Name + " mq.Input[" + normalizedType + "]"); err != nil {
			return err
		}
	}

	for i, output := range method.Outputs {
		outputName := getOutputName(output, i)

		if i != 0 || len(method.Inputs) != 0 {
			if _, err := w.WriteString(", "); err != nil {
				return err
			}
		}

		if _, err := w.WriteString(outputName + " mq.Output[" + output.Type + "]"); err != nil {
			return err
		}
	}

	if _, err := w.WriteString(") {\n"); err != nil {
		return err
	}

	lowerCaseName := getStringWithFirstLetterLowercase(method.Name)
	if _, err := w.WriteString("\tm." + lowerCaseName + "Setups = append(m." + lowerCaseName + "Setups, " + structName + method.Name + "Setup" + typeParamNames + "{\n"); err != nil {
		return err
	}

	for _, input := range method.Inputs {
		if _, err := w.WriteString("\t\t" + input.Name + ": " + input.Name + ",\n"); err != nil {
			return err
		}
	}

	for i, output := range method.Outputs {
		outputName := getOutputName(output, i)

		if _, err := w.WriteString("\t\t" + outputName + ": " + outputName + ",\n"); err != nil {
			return err
		}
	}

	if _, err := w.WriteString("\t})\n}\n\n"); err != nil {
		return err
	}

	return nil
}

func generateVerifyMethod(structName string, interfaceName string, interfaceTypeParams string, typeParamNames string, method parse.Method, w *bufio.Writer) error {
	// Add documentation comment
	comment := fmt.Sprintf("// Verify%s checks that %s was called the expected number of times with matching inputs.\n", method.Name, method.Name)
	if _, err := w.WriteString(comment); err != nil {
		return err
	}

	if _, err := w.WriteString("func (m *" + structName + typeParamNames + ") Verify" + method.Name + "(count mq.Count"); err != nil {
		return err
	}

	for _, input := range method.Inputs {
		if _, err := w.WriteString(", "); err != nil {
			return err
		}

		normalizedType := normalizeTypeForSetup(input.Type)
		if _, err := w.WriteString(input.Name + " mq.Input[" + normalizedType + "]"); err != nil {
			return err
		}
	}

	if _, err := w.WriteString(") {\n"); err != nil {
		return err
	}

	lowerCaseName := getStringWithFirstLetterLowercase(method.Name)

	// Only add condition check if there are inputs
	if len(method.Inputs) > 0 {
		if _, err := w.WriteString("\tc := 0\n\n"); err != nil {
			return err
		}

		if _, err := w.WriteString("\tfor _, call := range m." + lowerCaseName + "Calls {\n"); err != nil {
			return err
		}

		if _, err := w.WriteString("\t\tif "); err != nil {
			return err
		}

		for i, input := range method.Inputs {
			if i != 0 {
				if _, err := w.WriteString("&& "); err != nil {
					return err
				}
			}

			if _, err := w.WriteString(input.Name + ".Compare(call." + input.Name + ") "); err != nil {
				return err
			}
		}

		if _, err := w.WriteString("{\n\t\t\tc++\n\t\t}\n"); err != nil {
			return err
		}

		if _, err := w.WriteString("\t}\n\n"); err != nil {
			return err
		}
	} else {
		// For methods with no inputs, just count the length of calls
		if _, err := w.WriteString("\tc := len(m." + lowerCaseName + "Calls)\n\n"); err != nil {
			return err
		}
	}

	if _, err := w.WriteString("\tif !count.ShouldPass(c) {\n"); err != nil {
		return err
	}

	panicMsg := fmt.Sprintf("\t\tpanic(fmt.Sprintf(\"mock verification failed for %s.%s: expected count not met (actual: %%d)\", c))\n\t}\n}\n\n", interfaceName, method.Name)
	if _, err := w.WriteString(panicMsg); err != nil {
		return err
	}

	return nil
}

func generateActualMethod(structName string, interfaceTypeParams string, typeParamNames string, method parse.Method, w *bufio.Writer) error {
	if _, err := w.WriteString("func (m *" + structName + typeParamNames + ") " + method.Name + "("); err != nil {
		return err
	}

	for i, input := range method.Inputs {
		if i != 0 {
			if _, err := w.WriteString(", "); err != nil {
				return err
			}
		}

		if _, err := w.WriteString(input.Name + " " + input.Type); err != nil {
			return err
		}
	}

	if _, err := w.WriteString(") "); err != nil {
		return err
	}

	if len(method.Outputs) == 1 && method.Outputs[0].Name == "" {
		if _, err := w.WriteString(method.Outputs[0].Type + " {\n"); err != nil {
			return err
		}
	} else {
		if _, err := w.WriteString("("); err != nil {
			return err
		}

		for i, output := range method.Outputs {
			if i != 0 {
				if _, err := w.WriteString(", "); err != nil {
					return err
				}
			}

			if output.Name != "" {
				if _, err := w.WriteString(output.Name + " " + output.Type); err != nil {
					return err
				}
			} else {
				if _, err := w.WriteString(output.Type); err != nil {
					return err
				}
			}
		}

		if _, err := w.WriteString(") {\n"); err != nil {
			return err
		}
	}

	lowerCaseName := getStringWithFirstLetterLowercase(method.Name)

	// Only add condition check if there are inputs
	if len(method.Inputs) > 0 {
		if _, err := w.WriteString("\tfor _, setup := range m." + lowerCaseName + "Setups {\n"); err != nil {
			return err
		}

		if _, err := w.WriteString("\t\tif "); err != nil {
			return err
		}

		for i, input := range method.Inputs {
			if i != 0 {
				if _, err := w.WriteString("&& "); err != nil {
					return err
				}
			}

			if _, err := w.WriteString("setup." + input.Name + ".Compare(" + input.Name + ") "); err != nil {
				return err
			}
		}

		if _, err := w.WriteString("{\n"); err != nil {
			return err
		}

		if _, err := w.WriteString("\t\t\tm." + lowerCaseName + "Calls = append(m." + lowerCaseName + "Calls, " + structName + method.Name + "Call" + typeParamNames + "{\n"); err != nil {
			return err
		}

		for _, input := range method.Inputs {
			if _, err := w.WriteString("\t\t\t\t" + input.Name + ": " + input.Name + ",\n"); err != nil {
				return err
			}
		}

		if _, err := w.WriteString("\t\t\t})\n\n"); err != nil {
			return err
		}

		if _, err := w.WriteString("\t\t\treturn "); err != nil {
			return err
		}

		for i, output := range method.Outputs {
			outputName := getOutputName(output, i)

			if i != 0 {
				if _, err := w.WriteString(", "); err != nil {
					return err
				}
			}

			if _, err := w.WriteString("setup." + outputName + ".Value()"); err != nil {
				return err
			}
		}

		if _, err := w.WriteString("\n\t\t}\n\t}\n\n"); err != nil {
			return err
		}
	} else {
		// For methods with no inputs, just use the first setup if it exists
		if _, err := w.WriteString("\tif len(m." + lowerCaseName + "Setups) > 0 {\n"); err != nil {
			return err
		}

		if _, err := w.WriteString("\t\tm." + lowerCaseName + "Calls = append(m." + lowerCaseName + "Calls, " + structName + method.Name + "Call" + typeParamNames + "{})\n\n"); err != nil {
			return err
		}

		if _, err := w.WriteString("\t\treturn "); err != nil {
			return err
		}

		for i, output := range method.Outputs {
			outputName := getOutputName(output, i)

			if i != 0 {
				if _, err := w.WriteString(", "); err != nil {
					return err
				}
			}

			if _, err := w.WriteString("m." + lowerCaseName + "Setups[0]." + outputName + ".Value()"); err != nil {
				return err
			}
		}

		if _, err := w.WriteString("\n\t}\n\n"); err != nil {
			return err
		}
	}

	panicMsg := fmt.Sprintf("\tpanic(\"no mock setup found for %s.%s with the provided arguments\")\n}\n\n", structName, method.Name)
	if _, err := w.WriteString(panicMsg); err != nil {
		return err
	}

	return nil
}

func getOutputName(output parse.Field, i int) string {
	if output.Name != "" {
		// If the output has a name, use it
		return output.Name
	}

	// Generate a name for unnamed outputs
	// Use 'output' prefix instead of 'o' to avoid conflicts with user-defined names like 'o0'
	return fmt.Sprintf("output%v", i)
}

func getStringWithFirstLetterLowercase(s string) string {
	return strings.ToLower(s[:1]) + s[1:]
}

// normalizeTypeForSetup converts variadic types (...T) to slice types ([]T)
// for use in setup structs and verify methods, since we can't use variadic
// types as struct fields or in type parameters
func normalizeTypeForSetup(fieldType string) string {
	if strings.HasPrefix(fieldType, "...") {
		return "[]" + strings.TrimPrefix(fieldType, "...")
	}
	return fieldType
}

// getTypeParamNames extracts just the type parameter names from a type params string
// e.g., "[T any]" -> "[T]", "[K comparable, V any]" -> "[K, V]"
func getTypeParamNames(typeParams string) string {
	if typeParams == "" {
		return ""
	}

	// Remove brackets
	inner := strings.TrimPrefix(typeParams, "[")
	inner = strings.TrimSuffix(inner, "]")

	if inner == "" {
		return ""
	}

	// Split by comma
	parts := strings.Split(inner, ",")
	names := make([]string, 0, len(parts))

	for _, part := range parts {
		// Take first word (the name) before any constraint
		part = strings.TrimSpace(part)
		words := strings.Fields(part)
		if len(words) > 0 {
			names = append(names, words[0])
		}
	}

	if len(names) == 0 {
		return ""
	}

	return "[" + strings.Join(names, ", ") + "]"
}

// getMqImportPath attempts to find the module path for the mq library by looking for go.mod
func getMqImportPath() (string, error) {
	// Start from current directory and walk up to find go.mod
	dir, err := os.Getwd()
	if err != nil {
		return "", err
	}

	for {
		goModPath := filepath.Join(dir, "go.mod")
		if _, err := os.Stat(goModPath); err == nil {
			// Found go.mod, read it to get the module name
			content, err := os.ReadFile(goModPath)
			if err != nil {
				return "", err
			}

			lines := strings.Split(string(content), "\n")
			for _, line := range lines {
				line = strings.TrimSpace(line)
				if strings.HasPrefix(line, "module ") {
					return strings.TrimSpace(strings.TrimPrefix(line, "module")), nil
				}
			}
		}

		// Move up one directory
		parent := filepath.Dir(dir)
		if parent == dir {
			// Reached root without finding go.mod
			return "", fmt.Errorf("go.mod not found")
		}
		dir = parent
	}
}
