package generate

import (
	"bufio"
	"fmt"
	"os"
	"slices"
	"strings"

	"github.com/lukejoshuapark/mq/cmd/mq/text/parse"
)

func Generate(file parse.File, fileName string) error {
	f, err := os.Create(fileName)
	if err != nil {
		return err
	}
	defer f.Close()

	w := bufio.NewWriter(f)
	defer w.Flush()

	if err := generateHeader(file, w); err != nil {
		return err
	}

	return nil
}

func generateHeader(file parse.File, w *bufio.Writer) error {
	if _, err := w.WriteString("// This file was automatically generated by mq. DO NOT EDIT.\n"); err != nil {
		return err
	}

	if _, err := w.WriteString("package " + file.PackageName + "\n\nimport (\n"); err != nil {
		return err
	}

	if !slices.Contains(file.Imports, "fmt") {
		file.Imports = append(file.Imports, "fmt")
	}

	if !slices.Contains(file.Imports, "github.com/lukejoshuapark/mq") {
		file.Imports = append(file.Imports, "github.com/lukejoshuapark/mq")
	}

	slices.Sort(file.Imports)

	for _, imp := range file.Imports {
		if _, err := w.WriteString("\t\"" + imp + "\"\n"); err != nil {
			return err
		}
	}

	if _, err := w.WriteString(")\n\n"); err != nil {
		return err
	}

	return generateMockImplementations(file, w)
}

func generateMockImplementations(file parse.File, w *bufio.Writer) error {
	for _, intf := range file.Interfaces {
		if err := generateMockImplementation(intf, w); err != nil {
			return err
		}
	}

	return nil
}

func generateMockImplementation(intf parse.Interface, w *bufio.Writer) error {
	structName := "Mock" + intf.Name

	// Add documentation comment for the mock struct
	comment := fmt.Sprintf("// %s is a mock implementation of the %s interface.\n", structName, intf.Name)
	if _, err := w.WriteString(comment); err != nil {
		return err
	}

	if _, err := w.WriteString("type " + structName + intf.TypeParams + " struct {\n"); err != nil {
		return err
	}

	typeParamNames := getTypeParamNames(intf.TypeParams)

	for _, method := range intf.Methods {
		lowerCaseName := getStringWithFirstLetterLowercase(method.Name)
		if _, err := w.WriteString("\t" + lowerCaseName + "Setups []Mock" + intf.Name + method.Name + "Setup" + typeParamNames + "\n"); err != nil {
			return err
		}

		if _, err := w.WriteString("\t" + lowerCaseName + "Calls []Mock" + intf.Name + method.Name + "Call" + typeParamNames + "\n"); err != nil {
			return err
		}
	}

	if _, err := w.WriteString("}\n\n"); err != nil {
		return err
	}

	// Add documentation comment for the constructor
	comment = fmt.Sprintf("// New%s creates a new instance of %s.\n", structName, structName)
	if _, err := w.WriteString(comment); err != nil {
		return err
	}

	if _, err := w.WriteString("func New" + structName + intf.TypeParams + "() *" + structName + typeParamNames + " {\n\treturn &" + structName + typeParamNames + "{}\n}\n\n"); err != nil {
		return err
	}

	return generateMethods(structName, intf, w)
}

func generateMethods(structName string, intf parse.Interface, w *bufio.Writer) error {
	for _, method := range intf.Methods {
		if err := generateMethod(structName, intf.Name, intf.TypeParams, method, w); err != nil {
			return err
		}
	}

	return nil
}

func generateMethod(structName string, interfaceName string, interfaceTypeParams string, method parse.Method, w *bufio.Writer) error {
	typePrefix := structName + method.Name
	setupType := typePrefix + "Setup"
	callType := typePrefix + "Call"

	if _, err := w.WriteString("type " + setupType + interfaceTypeParams + " struct {\n"); err != nil {
		return err
	}

	for _, input := range method.Inputs {
		normalizedType := normalizeTypeForSetup(input.Type)
		if _, err := w.WriteString("\t" + input.Name + " mq.Input[" + normalizedType + "]\n"); err != nil {
			return err
		}
	}

	for i, output := range method.Outputs {
		outputName := getOutputName(output, i)
		if _, err := w.WriteString("\t" + outputName + " mq.Output[" + output.Type + "]\n"); err != nil {
			return err
		}
	}

	if _, err := w.WriteString("}\n\n"); err != nil {
		return err
	}

	if _, err := w.WriteString("type " + callType + interfaceTypeParams + " struct {\n"); err != nil {
		return err
	}

	for _, input := range method.Inputs {
		normalizedType := normalizeTypeForSetup(input.Type)
		if _, err := w.WriteString("\t" + input.Name + " " + normalizedType + "\n"); err != nil {
			return err
		}
	}

	if _, err := w.WriteString("}\n\n"); err != nil {
		return err
	}

	typeParamNames := getTypeParamNames(interfaceTypeParams)

	if err := generateSetupMethod(structName, interfaceTypeParams, typeParamNames, method, w); err != nil {
		return err
	}

	if err := generateVerifyMethod(structName, interfaceName, interfaceTypeParams, typeParamNames, method, w); err != nil {
		return err
	}

	if err := generateActualMethod(structName, interfaceTypeParams, typeParamNames, method, w); err != nil {
		return err
	}

	return nil
}

func generateSetupMethod(structName string, interfaceTypeParams string, typeParamNames string, method parse.Method, w *bufio.Writer) error {
	// Add documentation comment
	comment := fmt.Sprintf("// Setup%s configures the mock to return specific outputs when %s is called with matching inputs.\n", method.Name, method.Name)
	if _, err := w.WriteString(comment); err != nil {
		return err
	}

	if _, err := w.WriteString("func (m *" + structName + typeParamNames + ") Setup" + method.Name + "("); err != nil {
		return err
	}

	for i, input := range method.Inputs {
		if i != 0 {
			if _, err := w.WriteString(", "); err != nil {
				return err
			}
		}

		normalizedType := normalizeTypeForSetup(input.Type)
		if _, err := w.WriteString(input.Name + " mq.Input[" + normalizedType + "]"); err != nil {
			return err
		}
	}

	for i, output := range method.Outputs {
		outputName := getOutputName(output, i)

		if i != 0 || len(method.Inputs) != 0 {
			if _, err := w.WriteString(", "); err != nil {
				return err
			}
		}

		if _, err := w.WriteString(outputName + " mq.Output[" + output.Type + "]"); err != nil {
			return err
		}
	}

	if _, err := w.WriteString(") {\n"); err != nil {
		return err
	}

	lowerCaseName := getStringWithFirstLetterLowercase(method.Name)
	if _, err := w.WriteString("\tm." + lowerCaseName + "Setups = append(m." + lowerCaseName + "Setups, " + structName + method.Name + "Setup" + typeParamNames + "{\n"); err != nil {
		return err
	}

	for _, input := range method.Inputs {
		if _, err := w.WriteString("\t\t" + input.Name + ": " + input.Name + ",\n"); err != nil {
			return err
		}
	}

	for i, output := range method.Outputs {
		outputName := getOutputName(output, i)

		if _, err := w.WriteString("\t\t" + outputName + ": " + outputName + ",\n"); err != nil {
			return err
		}
	}

	if _, err := w.WriteString("\t})\n}\n\n"); err != nil {
		return err
	}

	return nil
}

func generateVerifyMethod(structName string, interfaceName string, interfaceTypeParams string, typeParamNames string, method parse.Method, w *bufio.Writer) error {
	// Add documentation comment
	comment := fmt.Sprintf("// Verify%s checks that %s was called the expected number of times with matching inputs.\n", method.Name, method.Name)
	if _, err := w.WriteString(comment); err != nil {
		return err
	}

	if _, err := w.WriteString("func (m *" + structName + typeParamNames + ") Verify" + method.Name + "(count mq.Count"); err != nil {
		return err
	}

	for _, input := range method.Inputs {
		if _, err := w.WriteString(", "); err != nil {
			return err
		}

		normalizedType := normalizeTypeForSetup(input.Type)
		if _, err := w.WriteString(input.Name + " mq.Input[" + normalizedType + "]"); err != nil {
			return err
		}
	}

	if _, err := w.WriteString(") {\n"); err != nil {
		return err
	}

	lowerCaseName := getStringWithFirstLetterLowercase(method.Name)

	// Only add condition check if there are inputs
	if len(method.Inputs) > 0 {
		if _, err := w.WriteString("\tc := 0\n\n"); err != nil {
			return err
		}

		if _, err := w.WriteString("\tfor _, call := range m." + lowerCaseName + "Calls {\n"); err != nil {
			return err
		}

		if _, err := w.WriteString("\t\tif "); err != nil {
			return err
		}

		for i, input := range method.Inputs {
			if i != 0 {
				if _, err := w.WriteString("&& "); err != nil {
					return err
				}
			}

			if _, err := w.WriteString(input.Name + ".Compare(call." + input.Name + ") "); err != nil {
				return err
			}
		}

		if _, err := w.WriteString("{\n\t\t\tc++\n\t\t}\n"); err != nil {
			return err
		}

		if _, err := w.WriteString("\t}\n\n"); err != nil {
			return err
		}
	} else {
		// For methods with no inputs, just count the length of calls
		if _, err := w.WriteString("\tc := len(m." + lowerCaseName + "Calls)\n\n"); err != nil {
			return err
		}
	}

	if _, err := w.WriteString("\tif !count.ShouldPass(c) {\n"); err != nil {
		return err
	}

	// Generate detailed error message with all calls made
	if _, err := w.WriteString("\t\tmsg := fmt.Sprintf(\"mock verification failed for " + interfaceName + "." + method.Name + ": expected count not met (actual: %d)\\n\", c)\n"); err != nil {
		return err
	}

	if _, err := w.WriteString("\t\tmsg += fmt.Sprintf(\"Calls made (%d total):\\n\", len(m." + lowerCaseName + "Calls))\n"); err != nil {
		return err
	}

	if len(method.Inputs) > 0 {
		if _, err := w.WriteString("\t\tfor i, call := range m." + lowerCaseName + "Calls {\n"); err != nil {
			return err
		}

		if _, err := w.WriteString("\t\t\tmsg += fmt.Sprintf(\"  [%d] "); err != nil {
			return err
		}

		for i, input := range method.Inputs {
			if i > 0 {
				if _, err := w.WriteString(", "); err != nil {
					return err
				}
			}
			formatVerb := getFormatVerb(input.Type)
			if _, err := w.WriteString(input.Name + "=" + formatVerb); err != nil {
				return err
			}
		}

		if _, err := w.WriteString("\\n\""); err != nil {
			return err
		}

		if _, err := w.WriteString(", i"); err != nil {
			return err
		}

		for _, input := range method.Inputs {
			if _, err := w.WriteString(", call." + input.Name); err != nil {
				return err
			}
		}

		if _, err := w.WriteString(")\n"); err != nil {
			return err
		}

		if _, err := w.WriteString("\t\t}\n"); err != nil {
			return err
		}
	} else {
		if _, err := w.WriteString("\t\tfor i := range m." + lowerCaseName + "Calls {\n"); err != nil {
			return err
		}

		if _, err := w.WriteString("\t\t\tmsg += fmt.Sprintf(\"  [%d] (no parameters)\\n\", i)\n"); err != nil {
			return err
		}

		if _, err := w.WriteString("\t\t}\n"); err != nil {
			return err
		}
	}

	if _, err := w.WriteString("\t\tpanic(msg)\n\t}\n}\n\n"); err != nil {
		return err
	}

	return nil
}

func generateActualMethod(structName string, interfaceTypeParams string, typeParamNames string, method parse.Method, w *bufio.Writer) error {
	if _, err := w.WriteString("func (m *" + structName + typeParamNames + ") " + method.Name + "("); err != nil {
		return err
	}

	for i, input := range method.Inputs {
		if i != 0 {
			if _, err := w.WriteString(", "); err != nil {
				return err
			}
		}

		if _, err := w.WriteString(input.Name + " " + input.Type); err != nil {
			return err
		}
	}

	if _, err := w.WriteString(") "); err != nil {
		return err
	}

	if len(method.Outputs) == 1 && method.Outputs[0].Name == "" {
		if _, err := w.WriteString(method.Outputs[0].Type + " {\n"); err != nil {
			return err
		}
	} else {
		if _, err := w.WriteString("("); err != nil {
			return err
		}

		for i, output := range method.Outputs {
			if i != 0 {
				if _, err := w.WriteString(", "); err != nil {
					return err
				}
			}

			if output.Name != "" {
				if _, err := w.WriteString(output.Name + " " + output.Type); err != nil {
					return err
				}
			} else {
				if _, err := w.WriteString(output.Type); err != nil {
					return err
				}
			}
		}

		if _, err := w.WriteString(") {\n"); err != nil {
			return err
		}
	}

	lowerCaseName := getStringWithFirstLetterLowercase(method.Name)

	// Only add condition check if there are inputs
	if len(method.Inputs) > 0 {
		if _, err := w.WriteString("\tfor _, setup := range m." + lowerCaseName + "Setups {\n"); err != nil {
			return err
		}

		if _, err := w.WriteString("\t\tif "); err != nil {
			return err
		}

		for i, input := range method.Inputs {
			if i != 0 {
				if _, err := w.WriteString("&& "); err != nil {
					return err
				}
			}

			if _, err := w.WriteString("setup." + input.Name + ".Compare(" + input.Name + ") "); err != nil {
				return err
			}
		}

		if _, err := w.WriteString("{\n"); err != nil {
			return err
		}

		if _, err := w.WriteString("\t\t\tm." + lowerCaseName + "Calls = append(m." + lowerCaseName + "Calls, " + structName + method.Name + "Call" + typeParamNames + "{\n"); err != nil {
			return err
		}

		for _, input := range method.Inputs {
			if _, err := w.WriteString("\t\t\t\t" + input.Name + ": " + input.Name + ",\n"); err != nil {
				return err
			}
		}

		if _, err := w.WriteString("\t\t\t})\n\n"); err != nil {
			return err
		}

		if _, err := w.WriteString("\t\t\treturn "); err != nil {
			return err
		}

		for i, output := range method.Outputs {
			outputName := getOutputName(output, i)

			if i != 0 {
				if _, err := w.WriteString(", "); err != nil {
					return err
				}
			}

			if _, err := w.WriteString("setup." + outputName + ".Value()"); err != nil {
				return err
			}
		}

		if _, err := w.WriteString("\n\t\t}\n\t}\n\n"); err != nil {
			return err
		}
	} else {
		// For methods with no inputs, just use the first setup if it exists
		if _, err := w.WriteString("\tif len(m." + lowerCaseName + "Setups) > 0 {\n"); err != nil {
			return err
		}

		if _, err := w.WriteString("\t\tm." + lowerCaseName + "Calls = append(m." + lowerCaseName + "Calls, " + structName + method.Name + "Call" + typeParamNames + "{})\n\n"); err != nil {
			return err
		}

		if _, err := w.WriteString("\t\treturn "); err != nil {
			return err
		}

		for i, output := range method.Outputs {
			outputName := getOutputName(output, i)

			if i != 0 {
				if _, err := w.WriteString(", "); err != nil {
					return err
				}
			}

			if _, err := w.WriteString("m." + lowerCaseName + "Setups[0]." + outputName + ".Value()"); err != nil {
				return err
			}
		}

		if _, err := w.WriteString("\n\t}\n\n"); err != nil {
			return err
		}
	}

	// Generate detailed error message with all setups registered
	if _, err := w.WriteString("\t// No matching setup found, generate helpful error message\n"); err != nil {
		return err
	}

	if len(method.Inputs) > 0 {
		if _, err := w.WriteString("\tmsg := fmt.Sprintf(\"no mock setup found for " + structName + "." + method.Name + " with the provided arguments: "); err != nil {
			return err
		}

		for i, input := range method.Inputs {
			if i > 0 {
				if _, err := w.WriteString(", "); err != nil {
					return err
				}
			}
			formatVerb := getFormatVerb(input.Type)
			if _, err := w.WriteString(input.Name + "=" + formatVerb); err != nil {
				return err
			}
		}

		if _, err := w.WriteString("\\n\""); err != nil {
			return err
		}

		for _, input := range method.Inputs {
			if _, err := w.WriteString(", " + input.Name); err != nil {
				return err
			}
		}

		if _, err := w.WriteString(")\n"); err != nil {
			return err
		}
	} else {
		if _, err := w.WriteString("\tmsg := \"no mock setup found for " + structName + "." + method.Name + "\\n\"\n"); err != nil {
			return err
		}
	}

	if _, err := w.WriteString("\tmsg += fmt.Sprintf(\"\\nSetups registered (%d total):\\n\", len(m." + lowerCaseName + "Setups))\n"); err != nil {
		return err
	}

	if len(method.Inputs) > 0 {
		if _, err := w.WriteString("\tfor i, setup := range m." + lowerCaseName + "Setups {\n"); err != nil {
			return err
		}

		if _, err := w.WriteString("\t\tmsg += fmt.Sprintf(\"  [%d] "); err != nil {
			return err
		}

		for i, input := range method.Inputs {
			if i > 0 {
				if _, err := w.WriteString(", "); err != nil {
					return err
				}
			}
			formatVerb := getFormatVerb(input.Type)
			if _, err := w.WriteString(input.Name + "=" + formatVerb); err != nil {
				return err
			}
		}

		if _, err := w.WriteString("\\n\""); err != nil {
			return err
		}

		if _, err := w.WriteString(", i"); err != nil {
			return err
		}

		for _, input := range method.Inputs {
			if _, err := w.WriteString(", setup." + input.Name); err != nil {
				return err
			}
		}

		if _, err := w.WriteString(")\n"); err != nil {
			return err
		}

		if _, err := w.WriteString("\t}\n"); err != nil {
			return err
		}
	} else {
		if _, err := w.WriteString("\tfor i := range m." + lowerCaseName + "Setups {\n"); err != nil {
			return err
		}

		if _, err := w.WriteString("\t\tmsg += fmt.Sprintf(\"  [%d] (no parameters)\\n\", i)\n"); err != nil {
			return err
		}

		if _, err := w.WriteString("\t}\n"); err != nil {
			return err
		}
	}

	if _, err := w.WriteString("\tif len(m." + lowerCaseName + "Setups) == 0 {\n"); err != nil {
		return err
	}

	if _, err := w.WriteString("\t\tmsg += \"  (no setups registered)\\n\"\n"); err != nil {
		return err
	}

	if _, err := w.WriteString("\t}\n"); err != nil {
		return err
	}

	if _, err := w.WriteString("\tpanic(msg)\n}\n\n"); err != nil {
		return err
	}

	return nil
}

func getOutputName(output parse.Field, i int) string {
	if output.Name != "" {
		// If the output has a name, use it
		return output.Name
	}

	// Generate a name for unnamed outputs
	// Use 'output' prefix instead of 'o' to avoid conflicts with user-defined names like 'o0'
	return fmt.Sprintf("output%v", i)
}

func getStringWithFirstLetterLowercase(s string) string {
	return strings.ToLower(s[:1]) + s[1:]
}

// normalizeTypeForSetup converts variadic types (...T) to slice types ([]T)
// for use in setup structs and verify methods, since we can't use variadic
// types as struct fields or in type parameters
func normalizeTypeForSetup(fieldType string) string {
	if strings.HasPrefix(fieldType, "...") {
		return "[]" + strings.TrimPrefix(fieldType, "...")
	}
	return fieldType
}

// getFormatVerb returns the appropriate fmt format verb for a field type.
// For function types, returns "%p" to print the pointer address.
// For other types, returns "%+v" for detailed formatting.
func getFormatVerb(fieldType string) string {
	if strings.HasPrefix(fieldType, "func(") || strings.Contains(fieldType, " func(") {
		return "%p"
	}
	return "%+v"
}

// getTypeParamNames extracts just the type parameter names from a type params string
// e.g., "[T any]" -> "[T]", "[K comparable, V any]" -> "[K, V]"
func getTypeParamNames(typeParams string) string {
	if typeParams == "" {
		return ""
	}

	// Remove brackets
	inner := strings.TrimPrefix(typeParams, "[")
	inner = strings.TrimSuffix(inner, "]")

	if inner == "" {
		return ""
	}

	// Split by comma
	parts := strings.Split(inner, ",")
	names := make([]string, 0, len(parts))

	for _, part := range parts {
		// Take first word (the name) before any constraint
		part = strings.TrimSpace(part)
		words := strings.Fields(part)
		if len(words) > 0 {
			names = append(names, words[0])
		}
	}

	if len(names) == 0 {
		return ""
	}

	return "[" + strings.Join(names, ", ") + "]"
}
