// This file was automatically generated by mq. DO NOT EDIT.
package multiple

import (
	"context"
	"fmt"
	"github.com/lukejoshuapark/mq"
)

// MockUserRepository is a mock implementation of the UserRepository interface.
type MockUserRepository struct {
	findByEmailSetups []MockUserRepositoryFindByEmailSetup
	findByEmailCalls []MockUserRepositoryFindByEmailCall
	createUserSetups []MockUserRepositoryCreateUserSetup
	createUserCalls []MockUserRepositoryCreateUserCall
	deleteUserSetups []MockUserRepositoryDeleteUserSetup
	deleteUserCalls []MockUserRepositoryDeleteUserCall
	listUsersSetups []MockUserRepositoryListUsersSetup
	listUsersCalls []MockUserRepositoryListUsersCall
}

// NewMockUserRepository creates a new instance of MockUserRepository.
func NewMockUserRepository() *MockUserRepository {
	return &MockUserRepository{}
}

type MockUserRepositoryFindByEmailSetup struct {
	ctx mq.Input[context.Context]
	email mq.Input[string]
	output0 mq.Output[*User]
	output1 mq.Output[error]
}

type MockUserRepositoryFindByEmailCall struct {
	ctx context.Context
	email string
}

// SetupFindByEmail configures the mock to return specific outputs when FindByEmail is called with matching inputs.
func (m *MockUserRepository) SetupFindByEmail(ctx mq.Input[context.Context], email mq.Input[string], output0 mq.Output[*User], output1 mq.Output[error]) {
	m.findByEmailSetups = append(m.findByEmailSetups, MockUserRepositoryFindByEmailSetup{
		ctx: ctx,
		email: email,
		output0: output0,
		output1: output1,
	})
}

// VerifyFindByEmail checks that FindByEmail was called the expected number of times with matching inputs.
func (m *MockUserRepository) VerifyFindByEmail(count mq.Count, ctx mq.Input[context.Context], email mq.Input[string]) {
	c := 0

	for _, call := range m.findByEmailCalls {
		if ctx.Compare(call.ctx) && email.Compare(call.email) {
			c++
		}
	}

	if !count.ShouldPass(c) {
		panic(fmt.Sprintf("mock verification failed for UserRepository.FindByEmail: expected count not met (actual: %d)", c))
	}
}

func (m *MockUserRepository) FindByEmail(ctx context.Context, email string) (*User, error) {
	for _, setup := range m.findByEmailSetups {
		if setup.ctx.Compare(ctx) && setup.email.Compare(email) {
			m.findByEmailCalls = append(m.findByEmailCalls, MockUserRepositoryFindByEmailCall{
				ctx: ctx,
				email: email,
			})

			return setup.output0.Value(), setup.output1.Value()
		}
	}

	panic("no mock setup found for MockUserRepository.FindByEmail with the provided arguments")
}

type MockUserRepositoryCreateUserSetup struct {
	ctx mq.Input[context.Context]
	user mq.Input[*User]
	output0 mq.Output[error]
}

type MockUserRepositoryCreateUserCall struct {
	ctx context.Context
	user *User
}

// SetupCreateUser configures the mock to return specific outputs when CreateUser is called with matching inputs.
func (m *MockUserRepository) SetupCreateUser(ctx mq.Input[context.Context], user mq.Input[*User], output0 mq.Output[error]) {
	m.createUserSetups = append(m.createUserSetups, MockUserRepositoryCreateUserSetup{
		ctx: ctx,
		user: user,
		output0: output0,
	})
}

// VerifyCreateUser checks that CreateUser was called the expected number of times with matching inputs.
func (m *MockUserRepository) VerifyCreateUser(count mq.Count, ctx mq.Input[context.Context], user mq.Input[*User]) {
	c := 0

	for _, call := range m.createUserCalls {
		if ctx.Compare(call.ctx) && user.Compare(call.user) {
			c++
		}
	}

	if !count.ShouldPass(c) {
		panic(fmt.Sprintf("mock verification failed for UserRepository.CreateUser: expected count not met (actual: %d)", c))
	}
}

func (m *MockUserRepository) CreateUser(ctx context.Context, user *User) error {
	for _, setup := range m.createUserSetups {
		if setup.ctx.Compare(ctx) && setup.user.Compare(user) {
			m.createUserCalls = append(m.createUserCalls, MockUserRepositoryCreateUserCall{
				ctx: ctx,
				user: user,
			})

			return setup.output0.Value()
		}
	}

	panic("no mock setup found for MockUserRepository.CreateUser with the provided arguments")
}

type MockUserRepositoryDeleteUserSetup struct {
	ctx mq.Input[context.Context]
	id mq.Input[int]
	output0 mq.Output[error]
}

type MockUserRepositoryDeleteUserCall struct {
	ctx context.Context
	id int
}

// SetupDeleteUser configures the mock to return specific outputs when DeleteUser is called with matching inputs.
func (m *MockUserRepository) SetupDeleteUser(ctx mq.Input[context.Context], id mq.Input[int], output0 mq.Output[error]) {
	m.deleteUserSetups = append(m.deleteUserSetups, MockUserRepositoryDeleteUserSetup{
		ctx: ctx,
		id: id,
		output0: output0,
	})
}

// VerifyDeleteUser checks that DeleteUser was called the expected number of times with matching inputs.
func (m *MockUserRepository) VerifyDeleteUser(count mq.Count, ctx mq.Input[context.Context], id mq.Input[int]) {
	c := 0

	for _, call := range m.deleteUserCalls {
		if ctx.Compare(call.ctx) && id.Compare(call.id) {
			c++
		}
	}

	if !count.ShouldPass(c) {
		panic(fmt.Sprintf("mock verification failed for UserRepository.DeleteUser: expected count not met (actual: %d)", c))
	}
}

func (m *MockUserRepository) DeleteUser(ctx context.Context, id int) error {
	for _, setup := range m.deleteUserSetups {
		if setup.ctx.Compare(ctx) && setup.id.Compare(id) {
			m.deleteUserCalls = append(m.deleteUserCalls, MockUserRepositoryDeleteUserCall{
				ctx: ctx,
				id: id,
			})

			return setup.output0.Value()
		}
	}

	panic("no mock setup found for MockUserRepository.DeleteUser with the provided arguments")
}

type MockUserRepositoryListUsersSetup struct {
	ctx mq.Input[context.Context]
	output0 mq.Output[[]*User]
	output1 mq.Output[error]
}

type MockUserRepositoryListUsersCall struct {
	ctx context.Context
}

// SetupListUsers configures the mock to return specific outputs when ListUsers is called with matching inputs.
func (m *MockUserRepository) SetupListUsers(ctx mq.Input[context.Context], output0 mq.Output[[]*User], output1 mq.Output[error]) {
	m.listUsersSetups = append(m.listUsersSetups, MockUserRepositoryListUsersSetup{
		ctx: ctx,
		output0: output0,
		output1: output1,
	})
}

// VerifyListUsers checks that ListUsers was called the expected number of times with matching inputs.
func (m *MockUserRepository) VerifyListUsers(count mq.Count, ctx mq.Input[context.Context]) {
	c := 0

	for _, call := range m.listUsersCalls {
		if ctx.Compare(call.ctx) {
			c++
		}
	}

	if !count.ShouldPass(c) {
		panic(fmt.Sprintf("mock verification failed for UserRepository.ListUsers: expected count not met (actual: %d)", c))
	}
}

func (m *MockUserRepository) ListUsers(ctx context.Context) ([]*User, error) {
	for _, setup := range m.listUsersSetups {
		if setup.ctx.Compare(ctx) {
			m.listUsersCalls = append(m.listUsersCalls, MockUserRepositoryListUsersCall{
				ctx: ctx,
			})

			return setup.output0.Value(), setup.output1.Value()
		}
	}

	panic("no mock setup found for MockUserRepository.ListUsers with the provided arguments")
}

