// This file was automatically generated by mq. DO NOT EDIT.
package maptypes

import (
	"fmt"
	"github.com/lukejoshuapark/mq"
)

// MockRegistry is a mock implementation of the Registry interface.
type MockRegistry struct {
	setSetups []MockRegistrySetSetup
	setCalls []MockRegistrySetCall
	getSetups []MockRegistryGetSetup
	getCalls []MockRegistryGetCall
	mergeSetups []MockRegistryMergeSetup
	mergeCalls []MockRegistryMergeCall
}

// NewMockRegistry creates a new instance of MockRegistry.
func NewMockRegistry() *MockRegistry {
	return &MockRegistry{}
}

type MockRegistrySetSetup struct {
	key mq.Input[string]
	tags mq.Input[map[string]string]
	output0 mq.Output[error]
}

type MockRegistrySetCall struct {
	key string
	tags map[string]string
}

// SetupSet configures the mock to return specific outputs when Set is called with matching inputs.
func (m *MockRegistry) SetupSet(key mq.Input[string], tags mq.Input[map[string]string], output0 mq.Output[error]) {
	m.setSetups = append(m.setSetups, MockRegistrySetSetup{
		key: key,
		tags: tags,
		output0: output0,
	})
}

// VerifySet checks that Set was called the expected number of times with matching inputs.
func (m *MockRegistry) VerifySet(count mq.Count, key mq.Input[string], tags mq.Input[map[string]string]) {
	c := 0

	for _, call := range m.setCalls {
		if key.Compare(call.key) && tags.Compare(call.tags) {
			c++
		}
	}

	if !count.ShouldPass(c) {
		msg := fmt.Sprintf("mock verification failed for Registry.Set: expected %s (count: %d)\n", count, c)
		msg += fmt.Sprintf("Calls made (%d total):\n", len(m.setCalls))
		for i, call := range m.setCalls {
			msg += fmt.Sprintf("  [%d] key=%+v, tags=%+v\n", i, call.key, call.tags)
		}
		panic(msg)
	}
}

func (m *MockRegistry) Set(key string, tags map[string]string) error {
	for _, setup := range m.setSetups {
		if setup.key.Compare(key) && setup.tags.Compare(tags) {
			m.setCalls = append(m.setCalls, MockRegistrySetCall{
				key: key,
				tags: tags,
			})

			return setup.output0.Value()
		}
	}

	// No matching setup found, generate helpful error message
	msg := fmt.Sprintf("no mock setup found for MockRegistry.Set with the provided arguments: key=%+v, tags=%+v\n", key, tags)
	msg += fmt.Sprintf("\nSetups registered (%d total):\n", len(m.setSetups))
	for i, setup := range m.setSetups {
		msg += fmt.Sprintf("  [%d] key=%s, tags=%s\n", i, setup.key, setup.tags)
	}
	if len(m.setSetups) == 0 {
		msg += "  (no setups registered)\n"
	}
	panic(msg)
}

type MockRegistryGetSetup struct {
	key mq.Input[string]
	output0 mq.Output[map[string]string]
	output1 mq.Output[error]
}

type MockRegistryGetCall struct {
	key string
}

// SetupGet configures the mock to return specific outputs when Get is called with matching inputs.
func (m *MockRegistry) SetupGet(key mq.Input[string], output0 mq.Output[map[string]string], output1 mq.Output[error]) {
	m.getSetups = append(m.getSetups, MockRegistryGetSetup{
		key: key,
		output0: output0,
		output1: output1,
	})
}

// VerifyGet checks that Get was called the expected number of times with matching inputs.
func (m *MockRegistry) VerifyGet(count mq.Count, key mq.Input[string]) {
	c := 0

	for _, call := range m.getCalls {
		if key.Compare(call.key) {
			c++
		}
	}

	if !count.ShouldPass(c) {
		msg := fmt.Sprintf("mock verification failed for Registry.Get: expected %s (count: %d)\n", count, c)
		msg += fmt.Sprintf("Calls made (%d total):\n", len(m.getCalls))
		for i, call := range m.getCalls {
			msg += fmt.Sprintf("  [%d] key=%+v\n", i, call.key)
		}
		panic(msg)
	}
}

func (m *MockRegistry) Get(key string) (map[string]string, error) {
	for _, setup := range m.getSetups {
		if setup.key.Compare(key) {
			m.getCalls = append(m.getCalls, MockRegistryGetCall{
				key: key,
			})

			return setup.output0.Value(), setup.output1.Value()
		}
	}

	// No matching setup found, generate helpful error message
	msg := fmt.Sprintf("no mock setup found for MockRegistry.Get with the provided arguments: key=%+v\n", key)
	msg += fmt.Sprintf("\nSetups registered (%d total):\n", len(m.getSetups))
	for i, setup := range m.getSetups {
		msg += fmt.Sprintf("  [%d] key=%s\n", i, setup.key)
	}
	if len(m.getSetups) == 0 {
		msg += "  (no setups registered)\n"
	}
	panic(msg)
}

type MockRegistryMergeSetup struct {
	base mq.Input[map[string]string]
	overlay mq.Input[map[string]string]
	output0 mq.Output[map[string]string]
}

type MockRegistryMergeCall struct {
	base map[string]string
	overlay map[string]string
}

// SetupMerge configures the mock to return specific outputs when Merge is called with matching inputs.
func (m *MockRegistry) SetupMerge(base mq.Input[map[string]string], overlay mq.Input[map[string]string], output0 mq.Output[map[string]string]) {
	m.mergeSetups = append(m.mergeSetups, MockRegistryMergeSetup{
		base: base,
		overlay: overlay,
		output0: output0,
	})
}

// VerifyMerge checks that Merge was called the expected number of times with matching inputs.
func (m *MockRegistry) VerifyMerge(count mq.Count, base mq.Input[map[string]string], overlay mq.Input[map[string]string]) {
	c := 0

	for _, call := range m.mergeCalls {
		if base.Compare(call.base) && overlay.Compare(call.overlay) {
			c++
		}
	}

	if !count.ShouldPass(c) {
		msg := fmt.Sprintf("mock verification failed for Registry.Merge: expected %s (count: %d)\n", count, c)
		msg += fmt.Sprintf("Calls made (%d total):\n", len(m.mergeCalls))
		for i, call := range m.mergeCalls {
			msg += fmt.Sprintf("  [%d] base=%+v, overlay=%+v\n", i, call.base, call.overlay)
		}
		panic(msg)
	}
}

func (m *MockRegistry) Merge(base map[string]string, overlay map[string]string) map[string]string {
	for _, setup := range m.mergeSetups {
		if setup.base.Compare(base) && setup.overlay.Compare(overlay) {
			m.mergeCalls = append(m.mergeCalls, MockRegistryMergeCall{
				base: base,
				overlay: overlay,
			})

			return setup.output0.Value()
		}
	}

	// No matching setup found, generate helpful error message
	msg := fmt.Sprintf("no mock setup found for MockRegistry.Merge with the provided arguments: base=%+v, overlay=%+v\n", base, overlay)
	msg += fmt.Sprintf("\nSetups registered (%d total):\n", len(m.mergeSetups))
	for i, setup := range m.mergeSetups {
		msg += fmt.Sprintf("  [%d] base=%s, overlay=%s\n", i, setup.base, setup.overlay)
	}
	if len(m.mergeSetups) == 0 {
		msg += "  (no setups registered)\n"
	}
	panic(msg)
}

