// This file was automatically generated by mq. DO NOT EDIT.
package namedreturns

import (
	"fmt"
	"github.com/lukejoshuapark/mq"
)

// MockDatabase is a mock implementation of the Database interface.
type MockDatabase struct {
	querySetups []MockDatabaseQuerySetup
	queryCalls []MockDatabaseQueryCall
	executeSetups []MockDatabaseExecuteSetup
	executeCalls []MockDatabaseExecuteCall
	connectSetups []MockDatabaseConnectSetup
	connectCalls []MockDatabaseConnectCall
}

// NewMockDatabase creates a new instance of MockDatabase.
func NewMockDatabase() *MockDatabase {
	return &MockDatabase{}
}

type MockDatabaseQuerySetup struct {
	sql mq.Input[string]
	result mq.Output[string]
	err mq.Output[error]
}

type MockDatabaseQueryCall struct {
	sql string
}

// SetupQuery configures the mock to return specific outputs when Query is called with matching inputs.
func (m *MockDatabase) SetupQuery(sql mq.Input[string], result mq.Output[string], err mq.Output[error]) {
	m.querySetups = append(m.querySetups, MockDatabaseQuerySetup{
		sql: sql,
		result: result,
		err: err,
	})
}

// VerifyQuery checks that Query was called the expected number of times with matching inputs.
func (m *MockDatabase) VerifyQuery(count mq.Count, sql mq.Input[string]) {
	c := 0

	for _, call := range m.queryCalls {
		if sql.Compare(call.sql) {
			c++
		}
	}

	if !count.ShouldPass(c) {
		panic(fmt.Sprintf("mock verification failed for Database.Query: expected count not met (actual: %d)", c))
	}
}

func (m *MockDatabase) Query(sql string) (result string, err error) {
	for _, setup := range m.querySetups {
		if setup.sql.Compare(sql) {
			m.queryCalls = append(m.queryCalls, MockDatabaseQueryCall{
				sql: sql,
			})

			return setup.result.Value(), setup.err.Value()
		}
	}

	panic("no mock setup found for MockDatabase.Query with the provided arguments")
}

type MockDatabaseExecuteSetup struct {
	cmd mq.Input[string]
	rowsAffected mq.Output[int]
	err mq.Output[error]
}

type MockDatabaseExecuteCall struct {
	cmd string
}

// SetupExecute configures the mock to return specific outputs when Execute is called with matching inputs.
func (m *MockDatabase) SetupExecute(cmd mq.Input[string], rowsAffected mq.Output[int], err mq.Output[error]) {
	m.executeSetups = append(m.executeSetups, MockDatabaseExecuteSetup{
		cmd: cmd,
		rowsAffected: rowsAffected,
		err: err,
	})
}

// VerifyExecute checks that Execute was called the expected number of times with matching inputs.
func (m *MockDatabase) VerifyExecute(count mq.Count, cmd mq.Input[string]) {
	c := 0

	for _, call := range m.executeCalls {
		if cmd.Compare(call.cmd) {
			c++
		}
	}

	if !count.ShouldPass(c) {
		panic(fmt.Sprintf("mock verification failed for Database.Execute: expected count not met (actual: %d)", c))
	}
}

func (m *MockDatabase) Execute(cmd string) (rowsAffected int, err error) {
	for _, setup := range m.executeSetups {
		if setup.cmd.Compare(cmd) {
			m.executeCalls = append(m.executeCalls, MockDatabaseExecuteCall{
				cmd: cmd,
			})

			return setup.rowsAffected.Value(), setup.err.Value()
		}
	}

	panic("no mock setup found for MockDatabase.Execute with the provided arguments")
}

type MockDatabaseConnectSetup struct {
	conn mq.Output[*Connection]
	err mq.Output[error]
}

type MockDatabaseConnectCall struct {
}

// SetupConnect configures the mock to return specific outputs when Connect is called with matching inputs.
func (m *MockDatabase) SetupConnect(conn mq.Output[*Connection], err mq.Output[error]) {
	m.connectSetups = append(m.connectSetups, MockDatabaseConnectSetup{
		conn: conn,
		err: err,
	})
}

// VerifyConnect checks that Connect was called the expected number of times with matching inputs.
func (m *MockDatabase) VerifyConnect(count mq.Count) {
	c := len(m.connectCalls)

	if !count.ShouldPass(c) {
		panic(fmt.Sprintf("mock verification failed for Database.Connect: expected count not met (actual: %d)", c))
	}
}

func (m *MockDatabase) Connect() (conn *Connection, err error) {
	if len(m.connectSetups) > 0 {
		m.connectCalls = append(m.connectCalls, MockDatabaseConnectCall{})

		return m.connectSetups[0].conn.Value(), m.connectSetups[0].err.Value()
	}

	panic("no mock setup found for MockDatabase.Connect with the provided arguments")
}

