// This file was automatically generated by mq. DO NOT EDIT.
package functiontypes

import (
	"fmt"
	"github.com/lukejoshuapark/mq"
)

// MockProcessor is a mock implementation of the Processor interface.
type MockProcessor struct {
	applySetups []MockProcessorApplySetup
	applyCalls []MockProcessorApplyCall
	filterSetups []MockProcessorFilterSetup
	filterCalls []MockProcessorFilterCall
	getHandlerSetups []MockProcessorGetHandlerSetup
	getHandlerCalls []MockProcessorGetHandlerCall
	transformSetups []MockProcessorTransformSetup
	transformCalls []MockProcessorTransformCall
}

// NewMockProcessor creates a new instance of MockProcessor.
func NewMockProcessor() *MockProcessor {
	return &MockProcessor{}
}

type MockProcessorApplySetup struct {
	fn mq.Input[func(int) int]
	output0 mq.Output[error]
}

type MockProcessorApplyCall struct {
	fn func(int) int
}

// SetupApply configures the mock to return specific outputs when Apply is called with matching inputs.
func (m *MockProcessor) SetupApply(fn mq.Input[func(int) int], output0 mq.Output[error]) {
	m.applySetups = append(m.applySetups, MockProcessorApplySetup{
		fn: fn,
		output0: output0,
	})
}

// VerifyApply checks that Apply was called the expected number of times with matching inputs.
func (m *MockProcessor) VerifyApply(count mq.Count, fn mq.Input[func(int) int]) {
	c := 0

	for _, call := range m.applyCalls {
		if fn.Compare(call.fn) {
			c++
		}
	}

	if !count.ShouldPass(c) {
		msg := fmt.Sprintf("mock verification failed for Processor.Apply: expected %s (count: %d)\n", count, c)
		msg += fmt.Sprintf("Calls made (%d total):\n", len(m.applyCalls))
		for i, call := range m.applyCalls {
			msg += fmt.Sprintf("  [%d] fn=%p\n", i, call.fn)
		}
		panic(msg)
	}
}

func (m *MockProcessor) Apply(fn func(int) int) error {
	for _, setup := range m.applySetups {
		if setup.fn.Compare(fn) {
			m.applyCalls = append(m.applyCalls, MockProcessorApplyCall{
				fn: fn,
			})

			return setup.output0.Value()
		}
	}

	// No matching setup found, generate helpful error message
	msg := fmt.Sprintf("no mock setup found for MockProcessor.Apply with the provided arguments: fn=%p\n", fn)
	msg += fmt.Sprintf("\nSetups registered (%d total):\n", len(m.applySetups))
	for i, setup := range m.applySetups {
		msg += fmt.Sprintf("  [%d] fn=%s\n", i, setup.fn)
	}
	if len(m.applySetups) == 0 {
		msg += "  (no setups registered)\n"
	}
	panic(msg)
}

type MockProcessorFilterSetup struct {
	items mq.Input[[]string]
	predicate mq.Input[func(string) bool]
	output0 mq.Output[[]string]
}

type MockProcessorFilterCall struct {
	items []string
	predicate func(string) bool
}

// SetupFilter configures the mock to return specific outputs when Filter is called with matching inputs.
func (m *MockProcessor) SetupFilter(items mq.Input[[]string], predicate mq.Input[func(string) bool], output0 mq.Output[[]string]) {
	m.filterSetups = append(m.filterSetups, MockProcessorFilterSetup{
		items: items,
		predicate: predicate,
		output0: output0,
	})
}

// VerifyFilter checks that Filter was called the expected number of times with matching inputs.
func (m *MockProcessor) VerifyFilter(count mq.Count, items mq.Input[[]string], predicate mq.Input[func(string) bool]) {
	c := 0

	for _, call := range m.filterCalls {
		if items.Compare(call.items) && predicate.Compare(call.predicate) {
			c++
		}
	}

	if !count.ShouldPass(c) {
		msg := fmt.Sprintf("mock verification failed for Processor.Filter: expected %s (count: %d)\n", count, c)
		msg += fmt.Sprintf("Calls made (%d total):\n", len(m.filterCalls))
		for i, call := range m.filterCalls {
			msg += fmt.Sprintf("  [%d] items=%+v, predicate=%p\n", i, call.items, call.predicate)
		}
		panic(msg)
	}
}

func (m *MockProcessor) Filter(items []string, predicate func(string) bool) []string {
	for _, setup := range m.filterSetups {
		if setup.items.Compare(items) && setup.predicate.Compare(predicate) {
			m.filterCalls = append(m.filterCalls, MockProcessorFilterCall{
				items: items,
				predicate: predicate,
			})

			return setup.output0.Value()
		}
	}

	// No matching setup found, generate helpful error message
	msg := fmt.Sprintf("no mock setup found for MockProcessor.Filter with the provided arguments: items=%+v, predicate=%p\n", items, predicate)
	msg += fmt.Sprintf("\nSetups registered (%d total):\n", len(m.filterSetups))
	for i, setup := range m.filterSetups {
		msg += fmt.Sprintf("  [%d] items=%s, predicate=%s\n", i, setup.items, setup.predicate)
	}
	if len(m.filterSetups) == 0 {
		msg += "  (no setups registered)\n"
	}
	panic(msg)
}

type MockProcessorGetHandlerSetup struct {
	output0 mq.Output[func(string) error]
}

type MockProcessorGetHandlerCall struct {
}

// SetupGetHandler configures the mock to return specific outputs when GetHandler is called with matching inputs.
func (m *MockProcessor) SetupGetHandler(output0 mq.Output[func(string) error]) {
	m.getHandlerSetups = append(m.getHandlerSetups, MockProcessorGetHandlerSetup{
		output0: output0,
	})
}

// VerifyGetHandler checks that GetHandler was called the expected number of times with matching inputs.
func (m *MockProcessor) VerifyGetHandler(count mq.Count) {
	c := len(m.getHandlerCalls)

	if !count.ShouldPass(c) {
		msg := fmt.Sprintf("mock verification failed for Processor.GetHandler: expected %s (count: %d)\n", count, c)
		msg += fmt.Sprintf("Calls made (%d total):\n", len(m.getHandlerCalls))
		for i := range m.getHandlerCalls {
			msg += fmt.Sprintf("  [%d] (no parameters)\n", i)
		}
		panic(msg)
	}
}

func (m *MockProcessor) GetHandler() func(string) error {
	if len(m.getHandlerSetups) > 0 {
		m.getHandlerCalls = append(m.getHandlerCalls, MockProcessorGetHandlerCall{})

		return m.getHandlerSetups[0].output0.Value()
	}

	// No matching setup found, generate helpful error message
	msg := "no mock setup found for MockProcessor.GetHandler\n"
	msg += fmt.Sprintf("\nSetups registered (%d total):\n", len(m.getHandlerSetups))
	for i := range m.getHandlerSetups {
		msg += fmt.Sprintf("  [%d] (no parameters)\n", i)
	}
	if len(m.getHandlerSetups) == 0 {
		msg += "  (no setups registered)\n"
	}
	panic(msg)
}

type MockProcessorTransformSetup struct {
	data mq.Input[interface{}]
	mapper mq.Input[func(interface{}) interface{}]
	output0 mq.Output[interface{}]
}

type MockProcessorTransformCall struct {
	data interface{}
	mapper func(interface{}) interface{}
}

// SetupTransform configures the mock to return specific outputs when Transform is called with matching inputs.
func (m *MockProcessor) SetupTransform(data mq.Input[interface{}], mapper mq.Input[func(interface{}) interface{}], output0 mq.Output[interface{}]) {
	m.transformSetups = append(m.transformSetups, MockProcessorTransformSetup{
		data: data,
		mapper: mapper,
		output0: output0,
	})
}

// VerifyTransform checks that Transform was called the expected number of times with matching inputs.
func (m *MockProcessor) VerifyTransform(count mq.Count, data mq.Input[interface{}], mapper mq.Input[func(interface{}) interface{}]) {
	c := 0

	for _, call := range m.transformCalls {
		if data.Compare(call.data) && mapper.Compare(call.mapper) {
			c++
		}
	}

	if !count.ShouldPass(c) {
		msg := fmt.Sprintf("mock verification failed for Processor.Transform: expected %s (count: %d)\n", count, c)
		msg += fmt.Sprintf("Calls made (%d total):\n", len(m.transformCalls))
		for i, call := range m.transformCalls {
			msg += fmt.Sprintf("  [%d] data=%+v, mapper=%p\n", i, call.data, call.mapper)
		}
		panic(msg)
	}
}

func (m *MockProcessor) Transform(data interface{}, mapper func(interface{}) interface{}) interface{} {
	for _, setup := range m.transformSetups {
		if setup.data.Compare(data) && setup.mapper.Compare(mapper) {
			m.transformCalls = append(m.transformCalls, MockProcessorTransformCall{
				data: data,
				mapper: mapper,
			})

			return setup.output0.Value()
		}
	}

	// No matching setup found, generate helpful error message
	msg := fmt.Sprintf("no mock setup found for MockProcessor.Transform with the provided arguments: data=%+v, mapper=%p\n", data, mapper)
	msg += fmt.Sprintf("\nSetups registered (%d total):\n", len(m.transformSetups))
	for i, setup := range m.transformSetups {
		msg += fmt.Sprintf("  [%d] data=%s, mapper=%s\n", i, setup.data, setup.mapper)
	}
	if len(m.transformSetups) == 0 {
		msg += "  (no setups registered)\n"
	}
	panic(msg)
}

