// This file was automatically generated by mq. DO NOT EDIT.
package basic

import (
	"fmt"
	"github.com/lukejoshuapark/mq"
)

// MockSimpleService is a mock implementation of the SimpleService interface.
type MockSimpleService struct {
	doSomethingSetups []MockSimpleServiceDoSomethingSetup
	doSomethingCalls []MockSimpleServiceDoSomethingCall
}

var _ SimpleService = &MockSimpleService{}

// NewMockSimpleService creates a new instance of MockSimpleService.
func NewMockSimpleService() *MockSimpleService {
	return &MockSimpleService{}
}

type MockSimpleServiceDoSomethingSetup struct {
	input mq.Input[string]
	output0 mq.Output[string]
	output1 mq.Output[error]
}

type MockSimpleServiceDoSomethingCall struct {
	input string
}

// SetupDoSomething configures the mock to return specific outputs when DoSomething is called with matching inputs.
func (m *MockSimpleService) SetupDoSomething(input mq.Input[string], output0 mq.Output[string], output1 mq.Output[error]) {
	m.doSomethingSetups = append(m.doSomethingSetups, MockSimpleServiceDoSomethingSetup{
		input: input,
		output0: output0,
		output1: output1,
	})
}

// VerifyDoSomething checks that DoSomething was called the expected number of times with matching inputs.
func (m *MockSimpleService) VerifyDoSomething(count mq.Count, input mq.Input[string]) {
	c := 0

	for _, call := range m.doSomethingCalls {
		if input.Compare(call.input) {
			c++
		}
	}

	if !count.ShouldPass(c) {
		panic(fmt.Sprintf("mock verification failed for SimpleService.DoSomething: expected count not met (actual: %d)", c))
	}
}

func (m *MockSimpleService) DoSomething(input string) (string, error) {
	for _, setup := range m.doSomethingSetups {
		if setup.input.Compare(input) {
			m.doSomethingCalls = append(m.doSomethingCalls, MockSimpleServiceDoSomethingCall{
				input: input,
			})

			return setup.output0.Value(), setup.output1.Value()
		}
	}

	panic("no mock setup found for MockSimpleService.DoSomething with the provided arguments")
}

