// This file was automatically generated by mq. DO NOT EDIT.
package complex

import (
	"context"
	"fmt"
	"github.com/lukejoshuapark/mq"
	"time"
)

// MockDataStore is a mock implementation of the DataStore interface.
type MockDataStore struct {
	querySetups []MockDataStoreQuerySetup
	queryCalls []MockDataStoreQueryCall
	saveSetups []MockDataStoreSaveSetup
	saveCalls []MockDataStoreSaveCall
	getMultipleSetups []MockDataStoreGetMultipleSetup
	getMultipleCalls []MockDataStoreGetMultipleCall
	processBatchSetups []MockDataStoreProcessBatchSetup
	processBatchCalls []MockDataStoreProcessBatchCall
}

// NewMockDataStore creates a new instance of MockDataStore.
func NewMockDataStore() *MockDataStore {
	return &MockDataStore{}
}

type MockDataStoreQuerySetup struct {
	ctx mq.Input[context.Context]
	query mq.Input[string]
	options mq.Input[*QueryOptions]
	output0 mq.Output[map[string]interface{}]
	output1 mq.Output[error]
}

type MockDataStoreQueryCall struct {
	ctx context.Context
	query string
	options *QueryOptions
}

// SetupQuery configures the mock to return specific outputs when Query is called with matching inputs.
func (m *MockDataStore) SetupQuery(ctx mq.Input[context.Context], query mq.Input[string], options mq.Input[*QueryOptions], output0 mq.Output[map[string]interface{}], output1 mq.Output[error]) {
	m.querySetups = append(m.querySetups, MockDataStoreQuerySetup{
		ctx: ctx,
		query: query,
		options: options,
		output0: output0,
		output1: output1,
	})
}

// VerifyQuery checks that Query was called the expected number of times with matching inputs.
func (m *MockDataStore) VerifyQuery(count mq.Count, ctx mq.Input[context.Context], query mq.Input[string], options mq.Input[*QueryOptions]) {
	c := 0

	for _, call := range m.queryCalls {
		if ctx.Compare(call.ctx) && query.Compare(call.query) && options.Compare(call.options) {
			c++
		}
	}

	if !count.ShouldPass(c) {
		msg := fmt.Sprintf("mock verification failed for DataStore.Query: expected %s (count: %d)\n", count, c)
		msg += fmt.Sprintf("Calls made (%d total):\n", len(m.queryCalls))
		for i, call := range m.queryCalls {
			msg += fmt.Sprintf("  [%d] ctx=%+v, query=%+v, options=%+v\n", i, call.ctx, call.query, call.options)
		}
		panic(msg)
	}
}

func (m *MockDataStore) Query(ctx context.Context, query string, options *QueryOptions) (map[string]interface{}, error) {
	for _, setup := range m.querySetups {
		if setup.ctx.Compare(ctx) && setup.query.Compare(query) && setup.options.Compare(options) {
			m.queryCalls = append(m.queryCalls, MockDataStoreQueryCall{
				ctx: ctx,
				query: query,
				options: options,
			})

			return setup.output0.Value(), setup.output1.Value()
		}
	}

	// No matching setup found, generate helpful error message
	msg := fmt.Sprintf("no mock setup found for MockDataStore.Query with the provided arguments: ctx=%+v, query=%+v, options=%+v\n", ctx, query, options)
	msg += fmt.Sprintf("\nSetups registered (%d total):\n", len(m.querySetups))
	for i, setup := range m.querySetups {
		msg += fmt.Sprintf("  [%d] ctx=%s, query=%s, options=%s\n", i, setup.ctx, setup.query, setup.options)
	}
	if len(m.querySetups) == 0 {
		msg += "  (no setups registered)\n"
	}
	panic(msg)
}

type MockDataStoreSaveSetup struct {
	ctx mq.Input[context.Context]
	key mq.Input[string]
	value mq.Input[interface{}]
	ttl mq.Input[time.Duration]
	output0 mq.Output[error]
}

type MockDataStoreSaveCall struct {
	ctx context.Context
	key string
	value interface{}
	ttl time.Duration
}

// SetupSave configures the mock to return specific outputs when Save is called with matching inputs.
func (m *MockDataStore) SetupSave(ctx mq.Input[context.Context], key mq.Input[string], value mq.Input[interface{}], ttl mq.Input[time.Duration], output0 mq.Output[error]) {
	m.saveSetups = append(m.saveSetups, MockDataStoreSaveSetup{
		ctx: ctx,
		key: key,
		value: value,
		ttl: ttl,
		output0: output0,
	})
}

// VerifySave checks that Save was called the expected number of times with matching inputs.
func (m *MockDataStore) VerifySave(count mq.Count, ctx mq.Input[context.Context], key mq.Input[string], value mq.Input[interface{}], ttl mq.Input[time.Duration]) {
	c := 0

	for _, call := range m.saveCalls {
		if ctx.Compare(call.ctx) && key.Compare(call.key) && value.Compare(call.value) && ttl.Compare(call.ttl) {
			c++
		}
	}

	if !count.ShouldPass(c) {
		msg := fmt.Sprintf("mock verification failed for DataStore.Save: expected %s (count: %d)\n", count, c)
		msg += fmt.Sprintf("Calls made (%d total):\n", len(m.saveCalls))
		for i, call := range m.saveCalls {
			msg += fmt.Sprintf("  [%d] ctx=%+v, key=%+v, value=%+v, ttl=%+v\n", i, call.ctx, call.key, call.value, call.ttl)
		}
		panic(msg)
	}
}

func (m *MockDataStore) Save(ctx context.Context, key string, value interface{}, ttl time.Duration) error {
	for _, setup := range m.saveSetups {
		if setup.ctx.Compare(ctx) && setup.key.Compare(key) && setup.value.Compare(value) && setup.ttl.Compare(ttl) {
			m.saveCalls = append(m.saveCalls, MockDataStoreSaveCall{
				ctx: ctx,
				key: key,
				value: value,
				ttl: ttl,
			})

			return setup.output0.Value()
		}
	}

	// No matching setup found, generate helpful error message
	msg := fmt.Sprintf("no mock setup found for MockDataStore.Save with the provided arguments: ctx=%+v, key=%+v, value=%+v, ttl=%+v\n", ctx, key, value, ttl)
	msg += fmt.Sprintf("\nSetups registered (%d total):\n", len(m.saveSetups))
	for i, setup := range m.saveSetups {
		msg += fmt.Sprintf("  [%d] ctx=%s, key=%s, value=%s, ttl=%s\n", i, setup.ctx, setup.key, setup.value, setup.ttl)
	}
	if len(m.saveSetups) == 0 {
		msg += "  (no setups registered)\n"
	}
	panic(msg)
}

type MockDataStoreGetMultipleSetup struct {
	ctx mq.Input[context.Context]
	keys mq.Input[[]string]
	output0 mq.Output[[]interface{}]
	output1 mq.Output[error]
}

type MockDataStoreGetMultipleCall struct {
	ctx context.Context
	keys []string
}

// SetupGetMultiple configures the mock to return specific outputs when GetMultiple is called with matching inputs.
func (m *MockDataStore) SetupGetMultiple(ctx mq.Input[context.Context], keys mq.Input[[]string], output0 mq.Output[[]interface{}], output1 mq.Output[error]) {
	m.getMultipleSetups = append(m.getMultipleSetups, MockDataStoreGetMultipleSetup{
		ctx: ctx,
		keys: keys,
		output0: output0,
		output1: output1,
	})
}

// VerifyGetMultiple checks that GetMultiple was called the expected number of times with matching inputs.
func (m *MockDataStore) VerifyGetMultiple(count mq.Count, ctx mq.Input[context.Context], keys mq.Input[[]string]) {
	c := 0

	for _, call := range m.getMultipleCalls {
		if ctx.Compare(call.ctx) && keys.Compare(call.keys) {
			c++
		}
	}

	if !count.ShouldPass(c) {
		msg := fmt.Sprintf("mock verification failed for DataStore.GetMultiple: expected %s (count: %d)\n", count, c)
		msg += fmt.Sprintf("Calls made (%d total):\n", len(m.getMultipleCalls))
		for i, call := range m.getMultipleCalls {
			msg += fmt.Sprintf("  [%d] ctx=%+v, keys=%+v\n", i, call.ctx, call.keys)
		}
		panic(msg)
	}
}

func (m *MockDataStore) GetMultiple(ctx context.Context, keys []string) ([]interface{}, error) {
	for _, setup := range m.getMultipleSetups {
		if setup.ctx.Compare(ctx) && setup.keys.Compare(keys) {
			m.getMultipleCalls = append(m.getMultipleCalls, MockDataStoreGetMultipleCall{
				ctx: ctx,
				keys: keys,
			})

			return setup.output0.Value(), setup.output1.Value()
		}
	}

	// No matching setup found, generate helpful error message
	msg := fmt.Sprintf("no mock setup found for MockDataStore.GetMultiple with the provided arguments: ctx=%+v, keys=%+v\n", ctx, keys)
	msg += fmt.Sprintf("\nSetups registered (%d total):\n", len(m.getMultipleSetups))
	for i, setup := range m.getMultipleSetups {
		msg += fmt.Sprintf("  [%d] ctx=%s, keys=%s\n", i, setup.ctx, setup.keys)
	}
	if len(m.getMultipleSetups) == 0 {
		msg += "  (no setups registered)\n"
	}
	panic(msg)
}

type MockDataStoreProcessBatchSetup struct {
	ctx mq.Input[context.Context]
	items mq.Input[[]interface{}]
	output0 mq.Output[int]
	output1 mq.Output[error]
}

type MockDataStoreProcessBatchCall struct {
	ctx context.Context
	items []interface{}
}

// SetupProcessBatch configures the mock to return specific outputs when ProcessBatch is called with matching inputs.
func (m *MockDataStore) SetupProcessBatch(ctx mq.Input[context.Context], items mq.Input[[]interface{}], output0 mq.Output[int], output1 mq.Output[error]) {
	m.processBatchSetups = append(m.processBatchSetups, MockDataStoreProcessBatchSetup{
		ctx: ctx,
		items: items,
		output0: output0,
		output1: output1,
	})
}

// VerifyProcessBatch checks that ProcessBatch was called the expected number of times with matching inputs.
func (m *MockDataStore) VerifyProcessBatch(count mq.Count, ctx mq.Input[context.Context], items mq.Input[[]interface{}]) {
	c := 0

	for _, call := range m.processBatchCalls {
		if ctx.Compare(call.ctx) && items.Compare(call.items) {
			c++
		}
	}

	if !count.ShouldPass(c) {
		msg := fmt.Sprintf("mock verification failed for DataStore.ProcessBatch: expected %s (count: %d)\n", count, c)
		msg += fmt.Sprintf("Calls made (%d total):\n", len(m.processBatchCalls))
		for i, call := range m.processBatchCalls {
			msg += fmt.Sprintf("  [%d] ctx=%+v, items=%+v\n", i, call.ctx, call.items)
		}
		panic(msg)
	}
}

func (m *MockDataStore) ProcessBatch(ctx context.Context, items ...interface{}) (int, error) {
	for _, setup := range m.processBatchSetups {
		if setup.ctx.Compare(ctx) && setup.items.Compare(items) {
			m.processBatchCalls = append(m.processBatchCalls, MockDataStoreProcessBatchCall{
				ctx: ctx,
				items: items,
			})

			return setup.output0.Value(), setup.output1.Value()
		}
	}

	// No matching setup found, generate helpful error message
	msg := fmt.Sprintf("no mock setup found for MockDataStore.ProcessBatch with the provided arguments: ctx=%+v, items=%+v\n", ctx, items)
	msg += fmt.Sprintf("\nSetups registered (%d total):\n", len(m.processBatchSetups))
	for i, setup := range m.processBatchSetups {
		msg += fmt.Sprintf("  [%d] ctx=%s, items=%s\n", i, setup.ctx, setup.items)
	}
	if len(m.processBatchSetups) == 0 {
		msg += "  (no setups registered)\n"
	}
	panic(msg)
}

