// This file was automatically generated by mq. DO NOT EDIT.
package erroronly

import (
	"fmt"
	"github.com/lukejoshuapark/mq"
)

// MockStore is a mock implementation of the Store interface.
type MockStore struct {
	saveSetups []MockStoreSaveSetup
	saveCalls []MockStoreSaveCall
	deleteSetups []MockStoreDeleteSetup
	deleteCalls []MockStoreDeleteCall
	connectSetups []MockStoreConnectSetup
	connectCalls []MockStoreConnectCall
}

// NewMockStore creates a new instance of MockStore.
func NewMockStore() *MockStore {
	return &MockStore{}
}

type MockStoreSaveSetup struct {
	key mq.Input[string]
	value mq.Input[string]
	output0 mq.Output[error]
}

type MockStoreSaveCall struct {
	key string
	value string
}

// SetupSave configures the mock to return specific outputs when Save is called with matching inputs.
func (m *MockStore) SetupSave(key mq.Input[string], value mq.Input[string], output0 mq.Output[error]) {
	m.saveSetups = append(m.saveSetups, MockStoreSaveSetup{
		key: key,
		value: value,
		output0: output0,
	})
}

// VerifySave checks that Save was called the expected number of times with matching inputs.
func (m *MockStore) VerifySave(count mq.Count, key mq.Input[string], value mq.Input[string]) {
	c := 0

	for _, call := range m.saveCalls {
		if key.Compare(call.key) && value.Compare(call.value) {
			c++
		}
	}

	if !count.ShouldPass(c) {
		msg := fmt.Sprintf("mock verification failed for Store.Save: expected %s (count: %d)\n", count, c)
		msg += fmt.Sprintf("Calls made (%d total):\n", len(m.saveCalls))
		for i, call := range m.saveCalls {
			msg += fmt.Sprintf("  [%d] key=%+v, value=%+v\n", i, call.key, call.value)
		}
		panic(msg)
	}
}

func (m *MockStore) Save(key string, value string) error {
	for _, setup := range m.saveSetups {
		if setup.key.Compare(key) && setup.value.Compare(value) {
			m.saveCalls = append(m.saveCalls, MockStoreSaveCall{
				key: key,
				value: value,
			})

			return setup.output0.Value()
		}
	}

	// No matching setup found, generate helpful error message
	msg := fmt.Sprintf("no mock setup found for MockStore.Save with the provided arguments: key=%+v, value=%+v\n", key, value)
	msg += fmt.Sprintf("\nSetups registered (%d total):\n", len(m.saveSetups))
	for i, setup := range m.saveSetups {
		msg += fmt.Sprintf("  [%d] key=%s, value=%s\n", i, setup.key, setup.value)
	}
	if len(m.saveSetups) == 0 {
		msg += "  (no setups registered)\n"
	}
	panic(msg)
}

type MockStoreDeleteSetup struct {
	key mq.Input[string]
	output0 mq.Output[error]
}

type MockStoreDeleteCall struct {
	key string
}

// SetupDelete configures the mock to return specific outputs when Delete is called with matching inputs.
func (m *MockStore) SetupDelete(key mq.Input[string], output0 mq.Output[error]) {
	m.deleteSetups = append(m.deleteSetups, MockStoreDeleteSetup{
		key: key,
		output0: output0,
	})
}

// VerifyDelete checks that Delete was called the expected number of times with matching inputs.
func (m *MockStore) VerifyDelete(count mq.Count, key mq.Input[string]) {
	c := 0

	for _, call := range m.deleteCalls {
		if key.Compare(call.key) {
			c++
		}
	}

	if !count.ShouldPass(c) {
		msg := fmt.Sprintf("mock verification failed for Store.Delete: expected %s (count: %d)\n", count, c)
		msg += fmt.Sprintf("Calls made (%d total):\n", len(m.deleteCalls))
		for i, call := range m.deleteCalls {
			msg += fmt.Sprintf("  [%d] key=%+v\n", i, call.key)
		}
		panic(msg)
	}
}

func (m *MockStore) Delete(key string) error {
	for _, setup := range m.deleteSetups {
		if setup.key.Compare(key) {
			m.deleteCalls = append(m.deleteCalls, MockStoreDeleteCall{
				key: key,
			})

			return setup.output0.Value()
		}
	}

	// No matching setup found, generate helpful error message
	msg := fmt.Sprintf("no mock setup found for MockStore.Delete with the provided arguments: key=%+v\n", key)
	msg += fmt.Sprintf("\nSetups registered (%d total):\n", len(m.deleteSetups))
	for i, setup := range m.deleteSetups {
		msg += fmt.Sprintf("  [%d] key=%s\n", i, setup.key)
	}
	if len(m.deleteSetups) == 0 {
		msg += "  (no setups registered)\n"
	}
	panic(msg)
}

type MockStoreConnectSetup struct {
	output0 mq.Output[error]
}

type MockStoreConnectCall struct {
}

// SetupConnect configures the mock to return specific outputs when Connect is called with matching inputs.
func (m *MockStore) SetupConnect(output0 mq.Output[error]) {
	m.connectSetups = append(m.connectSetups, MockStoreConnectSetup{
		output0: output0,
	})
}

// VerifyConnect checks that Connect was called the expected number of times with matching inputs.
func (m *MockStore) VerifyConnect(count mq.Count) {
	c := len(m.connectCalls)

	if !count.ShouldPass(c) {
		msg := fmt.Sprintf("mock verification failed for Store.Connect: expected %s (count: %d)\n", count, c)
		msg += fmt.Sprintf("Calls made (%d total):\n", len(m.connectCalls))
		for i := range m.connectCalls {
			msg += fmt.Sprintf("  [%d] (no parameters)\n", i)
		}
		panic(msg)
	}
}

func (m *MockStore) Connect() error {
	if len(m.connectSetups) > 0 {
		m.connectCalls = append(m.connectCalls, MockStoreConnectCall{})

		return m.connectSetups[0].output0.Value()
	}

	// No matching setup found, generate helpful error message
	msg := "no mock setup found for MockStore.Connect\n"
	msg += fmt.Sprintf("\nSetups registered (%d total):\n", len(m.connectSetups))
	for i := range m.connectSetups {
		msg += fmt.Sprintf("  [%d] (no parameters)\n", i)
	}
	if len(m.connectSetups) == 0 {
		msg += "  (no setups registered)\n"
	}
	panic(msg)
}

