// This file was automatically generated by mq. DO NOT EDIT.
package contextparam

import (
	"context"
	"fmt"
	"github.com/lukejoshuapark/mq"
)

// MockService is a mock implementation of the Service interface.
type MockService struct {
	fetchSetups []MockServiceFetchSetup
	fetchCalls []MockServiceFetchCall
	storeSetups []MockServiceStoreSetup
	storeCalls []MockServiceStoreCall
	pingSetups []MockServicePingSetup
	pingCalls []MockServicePingCall
}

// NewMockService creates a new instance of MockService.
func NewMockService() *MockService {
	return &MockService{}
}

type MockServiceFetchSetup struct {
	ctx mq.Input[context.Context]
	id mq.Input[string]
	output0 mq.Output[string]
	output1 mq.Output[error]
}

type MockServiceFetchCall struct {
	ctx context.Context
	id string
}

// SetupFetch configures the mock to return specific outputs when Fetch is called with matching inputs.
func (m *MockService) SetupFetch(ctx mq.Input[context.Context], id mq.Input[string], output0 mq.Output[string], output1 mq.Output[error]) {
	m.fetchSetups = append(m.fetchSetups, MockServiceFetchSetup{
		ctx: ctx,
		id: id,
		output0: output0,
		output1: output1,
	})
}

// VerifyFetch checks that Fetch was called the expected number of times with matching inputs.
func (m *MockService) VerifyFetch(count mq.Count, ctx mq.Input[context.Context], id mq.Input[string]) {
	c := 0

	for _, call := range m.fetchCalls {
		if ctx.Compare(call.ctx) && id.Compare(call.id) {
			c++
		}
	}

	if !count.ShouldPass(c) {
		msg := fmt.Sprintf("mock verification failed for Service.Fetch: expected %s (count: %d)\n", count, c)
		msg += fmt.Sprintf("Calls made (%d total):\n", len(m.fetchCalls))
		for i, call := range m.fetchCalls {
			msg += fmt.Sprintf("  [%d] ctx=%+v, id=%+v\n", i, call.ctx, call.id)
		}
		panic(msg)
	}
}

func (m *MockService) Fetch(ctx context.Context, id string) (string, error) {
	for _, setup := range m.fetchSetups {
		if setup.ctx.Compare(ctx) && setup.id.Compare(id) {
			m.fetchCalls = append(m.fetchCalls, MockServiceFetchCall{
				ctx: ctx,
				id: id,
			})

			return setup.output0.Value(), setup.output1.Value()
		}
	}

	// No matching setup found, generate helpful error message
	msg := fmt.Sprintf("no mock setup found for MockService.Fetch with the provided arguments: ctx=%+v, id=%+v\n", ctx, id)
	msg += fmt.Sprintf("\nSetups registered (%d total):\n", len(m.fetchSetups))
	for i, setup := range m.fetchSetups {
		msg += fmt.Sprintf("  [%d] ctx=%s, id=%s\n", i, setup.ctx, setup.id)
	}
	if len(m.fetchSetups) == 0 {
		msg += "  (no setups registered)\n"
	}
	panic(msg)
}

type MockServiceStoreSetup struct {
	ctx mq.Input[context.Context]
	key mq.Input[string]
	value mq.Input[string]
	output0 mq.Output[error]
}

type MockServiceStoreCall struct {
	ctx context.Context
	key string
	value string
}

// SetupStore configures the mock to return specific outputs when Store is called with matching inputs.
func (m *MockService) SetupStore(ctx mq.Input[context.Context], key mq.Input[string], value mq.Input[string], output0 mq.Output[error]) {
	m.storeSetups = append(m.storeSetups, MockServiceStoreSetup{
		ctx: ctx,
		key: key,
		value: value,
		output0: output0,
	})
}

// VerifyStore checks that Store was called the expected number of times with matching inputs.
func (m *MockService) VerifyStore(count mq.Count, ctx mq.Input[context.Context], key mq.Input[string], value mq.Input[string]) {
	c := 0

	for _, call := range m.storeCalls {
		if ctx.Compare(call.ctx) && key.Compare(call.key) && value.Compare(call.value) {
			c++
		}
	}

	if !count.ShouldPass(c) {
		msg := fmt.Sprintf("mock verification failed for Service.Store: expected %s (count: %d)\n", count, c)
		msg += fmt.Sprintf("Calls made (%d total):\n", len(m.storeCalls))
		for i, call := range m.storeCalls {
			msg += fmt.Sprintf("  [%d] ctx=%+v, key=%+v, value=%+v\n", i, call.ctx, call.key, call.value)
		}
		panic(msg)
	}
}

func (m *MockService) Store(ctx context.Context, key string, value string) error {
	for _, setup := range m.storeSetups {
		if setup.ctx.Compare(ctx) && setup.key.Compare(key) && setup.value.Compare(value) {
			m.storeCalls = append(m.storeCalls, MockServiceStoreCall{
				ctx: ctx,
				key: key,
				value: value,
			})

			return setup.output0.Value()
		}
	}

	// No matching setup found, generate helpful error message
	msg := fmt.Sprintf("no mock setup found for MockService.Store with the provided arguments: ctx=%+v, key=%+v, value=%+v\n", ctx, key, value)
	msg += fmt.Sprintf("\nSetups registered (%d total):\n", len(m.storeSetups))
	for i, setup := range m.storeSetups {
		msg += fmt.Sprintf("  [%d] ctx=%s, key=%s, value=%s\n", i, setup.ctx, setup.key, setup.value)
	}
	if len(m.storeSetups) == 0 {
		msg += "  (no setups registered)\n"
	}
	panic(msg)
}

type MockServicePingSetup struct {
	ctx mq.Input[context.Context]
	output0 mq.Output[error]
}

type MockServicePingCall struct {
	ctx context.Context
}

// SetupPing configures the mock to return specific outputs when Ping is called with matching inputs.
func (m *MockService) SetupPing(ctx mq.Input[context.Context], output0 mq.Output[error]) {
	m.pingSetups = append(m.pingSetups, MockServicePingSetup{
		ctx: ctx,
		output0: output0,
	})
}

// VerifyPing checks that Ping was called the expected number of times with matching inputs.
func (m *MockService) VerifyPing(count mq.Count, ctx mq.Input[context.Context]) {
	c := 0

	for _, call := range m.pingCalls {
		if ctx.Compare(call.ctx) {
			c++
		}
	}

	if !count.ShouldPass(c) {
		msg := fmt.Sprintf("mock verification failed for Service.Ping: expected %s (count: %d)\n", count, c)
		msg += fmt.Sprintf("Calls made (%d total):\n", len(m.pingCalls))
		for i, call := range m.pingCalls {
			msg += fmt.Sprintf("  [%d] ctx=%+v\n", i, call.ctx)
		}
		panic(msg)
	}
}

func (m *MockService) Ping(ctx context.Context) error {
	for _, setup := range m.pingSetups {
		if setup.ctx.Compare(ctx) {
			m.pingCalls = append(m.pingCalls, MockServicePingCall{
				ctx: ctx,
			})

			return setup.output0.Value()
		}
	}

	// No matching setup found, generate helpful error message
	msg := fmt.Sprintf("no mock setup found for MockService.Ping with the provided arguments: ctx=%+v\n", ctx)
	msg += fmt.Sprintf("\nSetups registered (%d total):\n", len(m.pingSetups))
	for i, setup := range m.pingSetups {
		msg += fmt.Sprintf("  [%d] ctx=%s\n", i, setup.ctx)
	}
	if len(m.pingSetups) == 0 {
		msg += "  (no setups registered)\n"
	}
	panic(msg)
}

